In [1]:
import json
import os
import re
import boto3
import pandas as pd
import logging

In [6]:
pd.set_option('display.max_rows', None)

In [2]:
with open("/home/rakshith/Data/IPL-2026/data/09_GTvsRR_meta.json", "r") as f:
    data = f.read()
metadata = json.loads(data)


df = pd.read_csv("/home/rakshith/Data/IPL-2026/data/09_GTvsRR_data.csv")

In [3]:
def get_toss_info(metadata):
    print("\nGetting Toss Info:\n")
    team1 = metadata["home_team"]
    team2 = metadata["away_team"]
    if metadata["toss_winner"] == team1:
        if metadata["toss_decision"] == "bat":
            batting_team = team1
            bowling_team = team2
        else:
            batting_team = team2
            bowling_team = team1
    else:
        if metadata["toss_decision"] == "bat":
            batting_team = team2
            bowling_team = team1
        else:
            batting_team = team1
            bowling_team = team2

    print(f"Batting: {batting_team}\nBowling: {bowling_team}\n")
    return batting_team, bowling_team

def get_innings(last_ball, new_ball):
    print("\nGetting Innings:\n")
    if last_ball == None:
        innings = 1
        score = 0
        wickets = 0
        target = 0
    else:
        if last_ball["innings"] == 1 and (int(last_ball["over"]) - int(new_ball["over"]) > 5):
            innings = 2
            score = 0
            wickets = 0
            target = last_ball["current_score"]
        elif last_ball["innings"] == 2 and (int(last_ball["over"]) - int(new_ball["over"]) > 5):
            innings = 3
            score = 0
            wickets = 0
            target = 0
        elif last_ball["innings"] == 3 and (int(last_ball["ball"]) - int(new_ball["ball"]) > 3):
            innings = 4
            score = 0
            wickets = 0
            target = last_ball["current_score"]
        else:
            innings = last_ball["innings"]
            score = last_ball["current_score"]
            wickets = last_ball["current_wickets"]
            target = last_ball["target"]
            
    return innings, score, wickets, target

In [21]:
def extract_runs(df):
    run_dict = {
        'no run': 0,
        '1 run': 1,
        '2 runs': 2,
        '3 runs': 3,
        'FOUR': 4,
        'four': 4,
        'SIX': 6,
        'six': 6
    }
    extras_dict = {
        'wide': 1,
        'no ball': 1,
        'no-ball': 1,
        'byes': 0,
        'leg byes': 0,
        'leg-byes': 0
    }

    runs = 0
    extra_runs = 0
    extra = 0
    extra_type = "N/A"
    rebowl = 0
    wicket = 0
    wicket_method = "Not Out"
    out_batsman = "N/A"

    ball_event = df['ball_event']
    event_info = df['event_info']

    if ball_event in run_dict.keys():
        runs = run_dict[ball_event]

    if ball_event in extras_dict.keys():
        extra = 1
        extra_runs = extras_dict[ball_event]
        rebowl = extras_dict[ball_event]
        extra_type = ball_event
        extra_event = event_info.split(';')[0]
        if extra_event in run_dict.keys():
            runs = run_dict[extra_event]

    elif ball_event == '5 wides':
        runs = 4
        extra_runs = 1
        extra = 1
        extra_type = 'wide'
        rebowl = 1

    elif ball_event.startswith('out'):
        wicket = 1
        if 'Run Out!' in ball_event:
            wicket_method = 'Run Out'
            out_batsman = ball_event.split('out ')[-1].split(' Run Out')[0]
        else:
            wicket_method = ball_event.split(' ')[1]
            out_batsman = df['batsman']

    data = {}
    data['match'] = df['match']
    data['data'] = df['date']
    data['time'] = df['time']
    data['over'] = df['over']
    data['ball'] = df['ball']
    data['bowler'] = df['bowler']
    data['batsman'] = df['batsman']
    data['runs'] = runs
    data['extra_runs'] = extra_runs
    data['extra'] = extra
    data['extra_type'] = extra_type
    data['rebowl'] = rebowl
    data['wicket'] = wicket
    data['wicket_method'] = wicket_method
    data['out_batsman'] = out_batsman
    data['total_runs'] = runs + extra_runs

    return data

In [22]:
extract_data = []

In [23]:
# batting_team, bowling_team = get_toss_info(metadata)

for index, row in df.iterrows():
    print(f"Extracting for: {row['over']}.{row['ball']}")
    extract_data.append(extract_runs(row))

Extracting for: 0.1
Extracting for: 0.1
Extracting for: 0.2
Extracting for: 0.3
Extracting for: 0.2
Extracting for: 0.3
Extracting for: 0.3
Extracting for: 0.4
Extracting for: 0.3
Extracting for: 0.4
Extracting for: 0.4
Extracting for: 0.5
Extracting for: 0.4
Extracting for: 0.5
Extracting for: 0.5
Extracting for: 0.6
Extracting for: 0.5
Extracting for: 0.6
Extracting for: 1.1
Extracting for: 1.2
Extracting for: 1.1
Extracting for: 1.2
Extracting for: 1.3
Extracting for: 1.4
Extracting for: 1.3
Extracting for: 1.4
Extracting for: 1.4
Extracting for: 1.4
Extracting for: 1.4
Extracting for: 1.4
Extracting for: 1.5
Extracting for: 1.6
Extracting for: 1.5
Extracting for: 1.6
Extracting for: 2.1
Extracting for: 2.2
Extracting for: 1.6
Extracting for: 2.1
Extracting for: 2.2
Extracting for: 2.3
Extracting for: 2.2
Extracting for: 2.3
Extracting for: 2.3
Extracting for: 2.3
Extracting for: 2.3
Extracting for: 2.3
Extracting for: 2.3
Extracting for: 2.4
Extracting for: 2.3
Extracting for: 2.4
Extracting for: 2.4
Extracting for: 2.5
Extracting for: 2.4
Extracting for: 2.5
Extracting for: 2.5
Extracting for: 2.6
Extracting for: 2.5
Extracting for: 2.6
Extracting for: 3.1
Extracting for: 3.2
Extracting for: 3.1
Extracting for: 3.2
Extracting for: 3.2
Extracting for: 3.2
Extracting for: 3.2
Extracting for: 3.2
Extracting for: 3.3
Extracting for: 3.4
Extracting for: 3.3
Extracting for: 3.4
Extracting for: 3.4
Extracting for: 3.5
Extracting for: 3.4
Extracting for: 3.5
Extracting for: 3.5
Extracting for: 3.6
Extracting for: 3.5
Extracting for: 3.6
Extracting for: 3.6
Extracting for: 4.1
Extracting for: 3.6
Extracting for: 4.1
Extracting for: 3.6
Extracting for: 4.1
Extracting for: 3.6
Extracting for: 4.1
Extracting for: 4.1
Extracting for: 4.2
Extracting for: 4.2
Extracting for: 4.3
Extracting for: 4.3
Extracting for: 4.4
Extracting for: 4.3
Extracting for: 4.4
Extracting for: 4.5
Extracting for: 4.6
Extracting for: 4.5
Extracting for: 4.6
Extracting for: 4.5
Extracting for: 4.6
Extracting for: 4.5
Extracting for: 4.6
Extracting for: 5.1
Extracting for: 5.2
Extracting for: 5.1
Extracting for: 5.2
Extracting for: 5.2
Extracting for: 5.3
Extracting for: 5.2
Extracting for: 5.3
Extracting for: 5.3
Extracting for: 5.4
Extracting for: 5.4
Extracting for: 5.5
Extracting for: 5.5
Extracting for: 5.6
Extracting for: 5.5
Extracting for: 5.6
Extracting for: 5.5
Extracting for: 5.6
Extracting for: 5.6
Extracting for: 6.1
Extracting for: 6.1
Extracting for: 6.2
Extracting for: 6.3
Extracting for: 6.4
Extracting for: 6.5
Extracting for: 6.6
Extracting for: 6.6
Extracting for: 7.1
Extracting for: 7.2
Extracting for: 7.3
Extracting for: 7.4
Extracting for: 7.5
Extracting for: 7.5
Extracting for: 7.6
Extracting for: 7.6
Extracting for: 8.1
Extracting for: 8.2
Extracting for: 8.3
Extracting for: 8.3
Extracting for: 8.4
Extracting for: 8.5
Extracting for: 8.6
Extracting for: 8.6
Extracting for: 9.1
Extracting for: 9.2
Extracting for: 9.3
Extracting for: 9.4
Extracting for: 9.5
Extracting for: 9.5
Extracting for: 9.6
Extracting for: 9.6
Extracting for: 10.1
Extracting for: 10.1
Extracting for: 10.2
Extracting for: 10.2
Extracting for: 10.3
Extracting for: 10.5
Extracting for: 10.6
Extracting for: 10.5
Extracting for: 10.6
Extracting for: 11.1
Extracting for: 11.2
Extracting for: 11.2
Extracting for: 11.3
Extracting for: 11.3
Extracting for: 11.4
Extracting for: 11.4
Extracting for: 11.5
Extracting for: 11.5
Extracting for: 11.6
Extracting for: 11.6
Extracting for: 12.1
Extracting for: 12.2
Extracting for: 12.3
Extracting for: 12.2
Extracting for: 12.3
Extracting for: 12.2
Extracting for: 12.3
Extracting for: 12.3
Extracting for: 12.4
Extracting for: 12.5
Extracting for: 12.6
Extracting for: 12.6
Extracting for: 13.1
Extracting for: 13.1
Extracting for: 13.2
Extracting for: 13.1
Extracting for: 13.2
Extracting for: 13.2
Extracting for: 13.3
Extracting for: 13.4
Extracting for: 13.4
Extracting for: 13.4
Extracting for: 13.5
Extracting for: 13.5
Extracting for: 13.6
Extracting for: 13.5
Extracting for: 13.6
Extracting for: 13.5
Extracting for: 13.6
Extracting for: 13.6
Extracting for: 14.1
Extracting for: 14.1
Extracting for: 14.1
Extracting for: 14.3
Extracting for: 14.4
Extracting for: 14.4
Extracting for: 14.5
Extracting for: 14.5
Extracting for: 14.6
Extracting for: 14.6
Extracting for: 15.1
Extracting for: 15.1
Extracting for: 15.2
Extracting for: 15.2
Extracting for: 15.3
Extracting for: 15.3
Extracting for: 15.4
Extracting for: 15.4
Extracting for: 15.5
Extracting for: 15.4
Extracting for: 15.5
Extracting for: 15.4
Extracting for: 15.5
Extracting for: 15.5
Extracting for: 15.6
Extracting for: 15.6
Extracting for: 16.1
Extracting for: 15.6
Extracting for: 16.1
Extracting for: 16.2
Extracting for: 16.3
Extracting for: 16.3
Extracting for: 16.4
Extracting for: 16.4
Extracting for: 16.5
Extracting for: 16.5
Extracting for: 16.6
Extracting for: 16.6
Extracting for: 17.1
Extracting for: 17.2
Extracting for: 17.3
Extracting for: 17.4
Extracting for: 17.4
Extracting for: 17.4
Extracting for: 17.5
Extracting for: 17.6
Extracting for: 17.6
Extracting for: 17.6
Extracting for: 17.6
Extracting for: 18.1
Extracting for: 18.2
Extracting for: 18.2
Extracting for: 18.3
Extracting for: 18.3
Extracting for: 18.4
Extracting for: 18.5
Extracting for: 18.6
Extracting for: 18.6
Extracting for: 19.1
Extracting for: 19.1
Extracting for: 19.2
Extracting for: 19.2
Extracting for: 19.3
Extracting for: 19.4
Extracting for: 19.5
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 0.1
Extracting for: 0.1
Extracting for: 0.2
Extracting for: 0.3
Extracting for: 0.3
Extracting for: 0.4
Extracting for: 0.5
Extracting for: 0.6
Extracting for: 0.6
Extracting for: 1.1
Extracting for: 1.1
Extracting for: 1.2
Extracting for: 1.2
Extracting for: 1.2
Extracting for: 1.3
Extracting for: 1.4
Extracting for: 1.5
Extracting for: 1.6
Extracting for: 1.5
Extracting for: 1.6
Extracting for: 2.1
Extracting for: 2.2
Extracting for: 2.2
Extracting for: 2.3
Extracting for: 2.4
Extracting for: 2.5
Extracting for: 2.5
Extracting for: 2.6
Extracting for: 2.6
Extracting for: 3.1
Extracting for: 3.2
Extracting for: 3.3
Extracting for: 3.3
Extracting for: 3.4
Extracting for: 3.5
Extracting for: 3.6
Extracting for: 3.6
Extracting for: 4.1
Extracting for: 4.1
Extracting for: 4.2
Extracting for: 4.2
Extracting for: 4.3
Extracting for: 4.4
Extracting for: 4.5
Extracting for: 4.5
Extracting for: 4.6
Extracting for: 4.6
Extracting for: 5.1
Extracting for: 5.1
Extracting for: 5.2
Extracting for: 5.2
Extracting for: 5.3
Extracting for: 5.4
Extracting for: 5.5
Extracting for: 5.5
Extracting for: 5.6
Extracting for: 5.6
Extracting for: 6.1
Extracting for: 6.2
Extracting for: 6.3
Extracting for: 6.4
Extracting for: 6.5
Extracting for: 6.5
Extracting for: 6.6
Extracting for: 6.6
Extracting for: 7.1
Extracting for: 7.3
Extracting for: 7.4
Extracting for: 7.4
Extracting for: 7.5
Extracting for: 7.5
Extracting for: 7.6
Extracting for: 7.5
Extracting for: 7.6
Extracting for: 7.5
Extracting for: 7.6
Extracting for: 7.5
Extracting for: 7.6
Extracting for: 7.5
Extracting for: 7.6
Extracting for: 8.2
Extracting for: 8.3
Extracting for: 8.3
Extracting for: 8.4
Extracting for: 8.4
Extracting for: 8.5
Extracting for: 8.5
Extracting for: 8.6
Extracting for: 8.6
Extracting for: 9.1
Extracting for: 9.1
Extracting for: 9.2
Extracting for: 9.2
Extracting for: 9.3
Extracting for: 9.4
Extracting for: 9.5
Extracting for: 9.5
Extracting for: 9.6
Extracting for: 10.1
Extracting for: 10.2
Extracting for: 10.2
Extracting for: 10.2
Extracting for: 10.3
Extracting for: 10.4
Extracting for: 10.3
Extracting for: 10.4
Extracting for: 10.4
Extracting for: 10.5
Extracting for: 10.5
Extracting for: 10.6
Extracting for: 10.6
Extracting for: 11.1
Extracting for: 11.2
Extracting for: 11.3
Extracting for: 11.4
Extracting for: 11.5
Extracting for: 11.5
Extracting for: 11.6
Extracting for: 11.6
Extracting for: 12.1
Extracting for: 11.6
Extracting for: 12.1
Extracting for: 12.1
Extracting for: 12.2
Extracting for: 12.2
Extracting for: 12.3
Extracting for: 12.3
Extracting for: 12.4
Extracting for: 12.5
Extracting for: 12.6
Extracting for: 12.5
Extracting for: 12.6
Extracting for: 12.6
Extracting for: 13.1
Extracting for: 12.6
Extracting for: 13.1
Extracting for: 13.1
Extracting for: 13.2
Extracting for: 13.3
Extracting for: 13.4
Extracting for: 13.4
Extracting for: 13.5
Extracting for: 13.5
Extracting for: 13.6
Extracting for: 13.6
Extracting for: 14.1
Extracting for: 14.1
Extracting for: 14.2
Extracting for: 14.2
Extracting for: 14.3
Extracting for: 14.3
Extracting for: 14.4
Extracting for: 14.3
Extracting for: 14.4
Extracting for: 14.4
Extracting for: 14.5
Extracting for: 14.5
Extracting for: 14.6
Extracting for: 14.6
Extracting for: 15.1
Extracting for: 15.1
Extracting for: 15.2
Extracting for: 15.3
Extracting for: 15.4
Extracting for: 15.4
Extracting for: 15.5
Extracting for: 15.5
Extracting for: 15.6
Extracting for: 15.5
Extracting for: 15.6
Extracting for: 15.5
Extracting for: 15.6
Extracting for: 15.5
Extracting for: 15.6
Extracting for: 15.5
Extracting for: 15.6
Extracting for: 15.5
Extracting for: 15.6
Extracting for: 15.6
Extracting for: 16.1
Extracting for: 15.6
Extracting for: 16.1
Extracting for: 16.2
Extracting for: 16.3
Extracting for: 16.2
Extracting for: 16.3
Extracting for: 16.5
Extracting for: 16.6
Extracting for: 16.5
Extracting for: 16.6
Extracting for: 16.5
Extracting for: 16.6
Extracting for: 16.5
Extracting for: 16.6
Extracting for: 17.1
Extracting for: 17.2
Extracting for: 17.1
Extracting for: 17.2
Extracting for: 17.1
Extracting for: 17.2
Extracting for: 17.2
Extracting for: 17.3
Extracting for: 17.3
Extracting for: 17.4
Extracting for: 17.3
Extracting for: 17.4
Extracting for: 17.4
Extracting for: 17.5
Extracting for: 17.4
Extracting for: 17.5
Extracting for: 17.5
Extracting for: 17.6
Extracting for: 17.5
Extracting for: 17.6
Extracting for: 17.6
Extracting for: 18.1
Extracting for: 17.6
Extracting for: 18.1
Extracting for: 18.1
Extracting for: 18.2
Extracting for: 18.1
Extracting for: 18.2
Extracting for: 18.2
Extracting for: 18.3
Extracting for: 18.2
Extracting for: 18.3
Extracting for: 18.2
Extracting for: 18.3
Extracting for: 18.3
Extracting for: 18.4
Extracting for: 18.4
Extracting for: 18.5
Extracting for: 18.5
Extracting for: 18.6
Extracting for: 18.5
Extracting for: 18.6
Extracting for: 19.1
Extracting for: 19.1
Extracting for: 19.1
Extracting for: 19.2
Extracting for: 19.2
Extracting for: 19.3
Extracting for: 19.3
Extracting for: 19.4
Extracting for: 19.4
Extracting for: 19.5
Extracting for: 19.4
Extracting for: 19.5
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6
Extracting for: 19.5
Extracting for: 19.6

In [24]:
extract_df = pd.DataFrame(extract_data)

In [25]:
extract_df.head()

,match,data,time,over,ball,bowler,batsman,runs,extra_runs,extra,extra_type,rebowl,wicket,wicket_method,out_batsman,total_runs
0,09_GTvsRR,April 04,19:00:01,0,1,Mohammed Siraj,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1
1,09_GTvsRR,April 04,19:00:01,0,1,Mohammed Siraj,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1
2,09_GTvsRR,April 04,19:00:01,0,2,Mohammed Siraj,Vaibhav Sooryavanshi,4,0,0,N/A,0,0,Not Out,N/A,4
3,09_GTvsRR,April 04,19:00:01,0,3,Mohammed Siraj,Vaibhav Sooryavanshi,0,0,0,N/A,0,0,Not Out,N/A,0
4,09_GTvsRR,April 04,19:00:01,0,2,Mohammed Siraj,Vaibhav Sooryavanshi,4,0,0,N/A,0,0,Not Out,N/A,4

In [26]:
extract_df.shape

(622, 16)

In [27]:
df2 = extract_df.drop_duplicates().reset_index(drop=True)

In [28]:
df2.head(500)

,match,data,time,over,ball,bowler,batsman,runs,extra_runs,extra,extra_type,rebowl,wicket,wicket_method,out_batsman,total_runs
0,09_GTvsRR,April 04,19:00:01,0,1,Mohammed Siraj,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1
1,09_GTvsRR,April 04,19:00:01,0,2,Mohammed Siraj,Vaibhav Sooryavanshi,4,0,0,N/A,0,0,Not Out,N/A,4
2,09_GTvsRR,April 04,19:00:01,0,3,Mohammed Siraj,Vaibhav Sooryavanshi,0,0,0,N/A,0,0,Not Out,N/A,0
3,09_GTvsRR,April 04,19:00:01,0,4,Mohammed Siraj,Vaibhav Sooryavanshi,4,0,0,N/A,0,0,Not Out,N/A,4
4,09_GTvsRR,April 04,19:00:01,0,5,Mohammed Siraj,Vaibhav Sooryavanshi,1,0,0,N/A,0,0,Not Out,N/A,1
5,09_GTvsRR,April 04,19:00:01,0,6,Mohammed Siraj,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0
6,09_GTvsRR,April 04,19:00:01,1,1,Kagiso Rabada,Vaibhav Sooryavanshi,1,0,0,N/A,0,0,Not Out,N/A,1
7,09_GTvsRR,April 04,19:00:01,1,2,Kagiso Rabada,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1
8,09_GTvsRR,April 04,19:00:01,1,3,Kagiso Rabada,Vaibhav Sooryavanshi,0,0,0,N/A,0,0,Not Out,N/A,0
9,09_GTvsRR,April 04,19:00:01,1,4,Kagiso Rabada,Vaibhav Sooryavanshi,0,1,1,wide,1,0,Not Out,N/A,1
10,09_GTvsRR,April 04,19:00:01,1,4,Kagiso Rabada,Vaibhav Sooryavanshi,0,0,0,N/A,0,0,Not Out,N/A,0
11,09_GTvsRR,April 04,19:00:01,1,5,Kagiso Rabada,Vaibhav Sooryavanshi,4,0,0,N/A,0,0,Not Out,N/A,4
12,09_GTvsRR,April 04,19:00:01,1,6,Kagiso Rabada,Vaibhav Sooryavanshi,0,0,0,N/A,0,0,Not Out,N/A,0
13,09_GTvsRR,April 04,19:00:01,2,1,Mohammed Siraj,Yashasvi Jaiswal,6,0,0,N/A,0,0,Not Out,N/A,6
14,09_GTvsRR,April 04,19:00:01,2,2,Mohammed Siraj,Yashasvi Jaiswal,4,0,0,N/A,0,0,Not Out,N/A,4
15,09_GTvsRR,April 04,19:00:01,2,3,Mohammed Siraj,Yashasvi Jaiswal,0,1,1,wide,1,0,Not Out,N/A,1
16,09_GTvsRR,April 04,19:00:01,2,3,Mohammed Siraj,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0
17,09_GTvsRR,April 04,19:00:01,2,4,Mohammed Siraj,Yashasvi Jaiswal,4,0,0,N/A,0,0,Not Out,N/A,4
18,09_GTvsRR,April 04,19:00:01,2,5,Mohammed Siraj,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0
19,09_GTvsRR,April 04,19:00:01,2,6,Mohammed Siraj,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0
20,09_GTvsRR,April 04,19:00:01,3,1,Kagiso Rabada,Vaibhav Sooryavanshi,0,0,0,N/A,0,0,Not Out,N/A,0
21,09_GTvsRR,April 04,19:00:01,3,2,Kagiso Rabada,Vaibhav Sooryavanshi,0,1,1,wide,1,0,Not Out,N/A,1
22,09_GTvsRR,April 04,19:00:01,3,2,Kagiso Rabada,Vaibhav Sooryavanshi,4,0,0,N/A,0,0,Not Out,N/A,4
23,09_GTvsRR,April 04,19:00:01,3,3,Kagiso Rabada,Vaibhav Sooryavanshi,1,0,0,N/A,0,0,Not Out,N/A,1
24,09_GTvsRR,April 04,19:00:01,3,4,Kagiso Rabada,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0
25,09_GTvsRR,April 04,19:00:01,3,5,Kagiso Rabada,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0
26,09_GTvsRR,April 04,19:00:01,3,6,Kagiso Rabada,Yashasvi Jaiswal,6,0,0,N/A,0,0,Not Out,N/A,6
27,09_GTvsRR,April 04,19:00:01,4,1,Ashok Sharma,Vaibhav Sooryavanshi,4,0,0,N/A,0,0,Not Out,N/A,4
28,09_GTvsRR,April 04,19:00:01,4,2,Ashok Sharma,Vaibhav Sooryavanshi,6,0,0,N/A,0,0,Not Out,N/A,6
29,09_GTvsRR,April 04,19:00:01,4,3,Ashok Sharma,Vaibhav Sooryavanshi,1,0,0,N/A,0,0,Not Out,N/A,1
30,09_GTvsRR,April 04,19:00:01,4,4,Ashok Sharma,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0
31,09_GTvsRR,April 04,19:00:01,4,5,Ashok Sharma,Yashasvi Jaiswal,2,0,0,N/A,0,0,Not Out,N/A,2
32,09_GTvsRR,April 04,19:00:01,4,6,Ashok Sharma,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0
33,09_GTvsRR,April 04,19:00:01,5,1,Prasidh Krishna,Vaibhav Sooryavanshi,1,0,0,N/A,0,0,Not Out,N/A,1
34,09_GTvsRR,April 04,19:00:01,5,2,Prasidh Krishna,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0
35,09_GTvsRR,April 04,19:00:01,5,3,Prasidh Krishna,Yashasvi Jaiswal,6,0,0,N/A,0,0,Not Out,N/A,6
36,09_GTvsRR,April 04,19:00:01,5,4,Prasidh Krishna,Yashasvi Jaiswal,4,0,0,N/A,0,0,Not Out,N/A,4
37,09_GTvsRR,April 04,19:00:01,5,5,Prasidh Krishna,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1
38,09_GTvsRR,April 04,19:00:01,5,6,Prasidh Krishna,Vaibhav Sooryavanshi,0,0,0,N/A,0,0,Not Out,N/A,0
39,09_GTvsRR,April 04,19:00:01,6,1,Rashid Khan,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1
40,09_GTvsRR,April 04,19:00:01,6,2,Rashid Khan,Vaibhav Sooryavanshi,0,0,0,N/A,0,1,Caught,Vaibhav Sooryavanshi,0
41,09_GTvsRR,April 04,19:00:01,6,3,Rashid Khan,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
42,09_GTvsRR,April 04,19:00:01,6,4,Rashid Khan,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1
43,09_GTvsRR,April 04,19:00:01,6,5,Rashid Khan,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
44,09_GTvsRR,April 04,19:00:01,6,6,Rashid Khan,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1
45,09_GTvsRR,April 04,19:00:01,7,1,Prasidh Krishna,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0
46,09_GTvsRR,April 04,19:00:01,7,2,Prasidh Krishna,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0
47,09_GTvsRR,April 04,19:00:01,7,3,Prasidh Krishna,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1
48,09_GTvsRR,April 04,19:00:01,7,4,Prasidh Krishna,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0
49,09_GTvsRR,April 04,19:00:01,7,5,Prasidh Krishna,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
50,09_GTvsRR,April 04,19:00:01,7,6,Prasidh Krishna,Yashasvi Jaiswal,4,0,0,N/A,0,0,Not Out,N/A,4
51,09_GTvsRR,April 04,19:00:01,8,1,Rashid Khan,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
52,09_GTvsRR,April 04,19:00:01,8,2,Rashid Khan,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1
53,09_GTvsRR,April 04,19:00:01,8,3,Rashid Khan,Dhruv Jurel,4,1,1,wide,1,0,Not Out,N/A,5
54,09_GTvsRR,April 04,19:00:01,8,3,Rashid Khan,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
55,09_GTvsRR,April 04,19:00:01,8,4,Rashid Khan,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1
56,09_GTvsRR,April 04,19:00:01,8,5,Rashid Khan,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
57,09_GTvsRR,April 04,19:00:01,8,6,Rashid Khan,Yashasvi Jaiswal,2,0,0,N/A,0,0,Not Out,N/A,2
58,09_GTvsRR,April 04,19:00:01,9,1,Ashok Sharma,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0
59,09_GTvsRR,April 04,19:00:01,9,2,Ashok Sharma,Dhruv Jurel,4,0,0,N/A,0,0,Not Out,N/A,4
60,09_GTvsRR,April 04,19:00:01,9,3,Ashok Sharma,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0
61,09_GTvsRR,April 04,19:00:01,9,4,Ashok Sharma,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0
62,09_GTvsRR,April 04,19:00:01,9,5,Ashok Sharma,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
63,09_GTvsRR,April 04,19:00:01,9,6,Ashok Sharma,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0
64,09_GTvsRR,April 04,19:00:01,10,1,Rashid Khan,Dhruv Jurel,4,0,0,N/A,0,0,Not Out,N/A,4
65,09_GTvsRR,April 04,19:00:01,10,2,Rashid Khan,Dhruv Jurel,2,0,0,N/A,0,0,Not Out,N/A,2
66,09_GTvsRR,April 04,19:00:01,10,3,Rashid Khan,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0
67,09_GTvsRR,April 04,19:00:01,10,5,Rashid Khan,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0
68,09_GTvsRR,April 04,19:00:01,10,6,Rashid Khan,Dhruv Jurel,4,0,0,N/A,0,0,Not Out,N/A,4
69,09_GTvsRR,April 04,19:00:01,11,1,Mohammed Siraj,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0
70,09_GTvsRR,April 04,19:00:01,11,2,Mohammed Siraj,Yashasvi Jaiswal,4,0,0,N/A,0,0,Not Out,N/A,4
71,09_GTvsRR,April 04,19:00:01,11,3,Mohammed Siraj,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1
72,09_GTvsRR,April 04,19:00:01,11,3,Mohammed Siraj,Yashasvi Jaiswal,1,0,1,leg byes,0,0,Not Out,N/A,1
73,09_GTvsRR,April 04,19:00:01,11,4,Mohammed Siraj,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0
74,09_GTvsRR,April 04,19:00:01,11,5,Mohammed Siraj,Dhruv Jurel,4,0,0,N/A,0,0,Not Out,N/A,4
75,09_GTvsRR,April 04,19:00:01,11,6,Mohammed Siraj,Dhruv Jurel,6,0,0,N/A,0,0,Not Out,N/A,6
76,09_GTvsRR,April 04,19:00:01,12,1,Kagiso Rabada,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0
77,09_GTvsRR,April 04,19:00:01,12,2,Kagiso Rabada,Yashasvi Jaiswal,4,0,0,N/A,0,0,Not Out,N/A,4
78,09_GTvsRR,April 04,19:00:01,12,3,Kagiso Rabada,Yashasvi Jaiswal,0,0,0,N/A,0,1,Bowled!!,Yashasvi Jaiswal,0
79,09_GTvsRR,April 04,19:00:01,12,4,Kagiso Rabada,Riyan Parag,6,0,0,N/A,0,0,Not Out,N/A,6
80,09_GTvsRR,April 04,19:00:01,12,5,Kagiso Rabada,Riyan Parag,2,0,0,N/A,0,0,Not Out,N/A,2
81,09_GTvsRR,April 04,19:00:01,12,6,Kagiso Rabada,Riyan Parag,0,0,0,N/A,0,0,Not Out,N/A,0
82,09_GTvsRR,April 04,19:00:01,13,1,Prasidh Krishna,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
83,09_GTvsRR,April 04,19:00:01,13,2,Prasidh Krishna,Riyan Parag,0,0,0,N/A,0,1,Caught,Riyan Parag,0
84,09_GTvsRR,April 04,19:00:01,13,3,Prasidh Krishna,Shimron Hetmyer,0,0,0,N/A,0,0,Not Out,N/A,0
85,09_GTvsRR,April 04,19:00:01,13,4,Prasidh Krishna,Shimron Hetmyer,0,1,1,wide,1,0,Not Out,N/A,1
86,09_GTvsRR,April 04,19:00:01,13,4,Prasidh Krishna,Shimron Hetmyer,0,0,0,N/A,0,0,Not Out,N/A,0
87,09_GTvsRR,April 04,19:00:01,13,5,Prasidh Krishna,Shimron Hetmyer,6,0,0,N/A,0,0,Not Out,N/A,6
88,09_GTvsRR,April 04,19:00:01,13,6,Prasidh Krishna,Shimron Hetmyer,6,0,0,N/A,0,0,Not Out,N/A,6
89,09_GTvsRR,April 04,19:00:01,14,1,Rashid Khan,Dhruv Jurel,0,1,1,wide,1,0,Not Out,N/A,1
90,09_GTvsRR,April 04,19:00:01,14,1,Rashid Khan,Dhruv Jurel,6,0,0,N/A,0,0,Not Out,N/A,6
91,09_GTvsRR,April 04,19:00:01,14,3,Rashid Khan,Shimron Hetmyer,1,0,0,N/A,0,0,Not Out,N/A,1
92,09_GTvsRR,April 04,19:00:01,14,4,Rashid Khan,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
93,09_GTvsRR,April 04,19:00:01,14,5,Rashid Khan,Shimron Hetmyer,1,0,0,N/A,0,0,Not Out,N/A,1
94,09_GTvsRR,April 04,19:00:01,14,6,Rashid Khan,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
95,09_GTvsRR,April 04,19:00:01,15,1,Ashok Sharma,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
96,09_GTvsRR,April 04,19:00:01,15,2,Ashok Sharma,Shimron Hetmyer,4,0,0,N/A,0,0,Not Out,N/A,4
97,09_GTvsRR,April 04,19:00:01,15,3,Ashok Sharma,Shimron Hetmyer,0,0,0,N/A,0,1,Caught,Shimron Hetmyer,0
98,09_GTvsRR,April 04,19:00:01,15,4,Ashok Sharma,Donovan Ferreira,0,0,0,N/A,0,0,Not Out,N/A,0
99,09_GTvsRR,April 04,19:00:01,15,5,Ashok Sharma,Donovan Ferreira,1,0,0,N/A,0,0,Not Out,N/A,1
100,09_GTvsRR,April 04,19:00:01,15,6,Ashok Sharma,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0
101,09_GTvsRR,April 04,19:00:01,16,1,Kagiso Rabada,Donovan Ferreira,0,0,0,N/A,0,1,Caught,Donovan Ferreira,0
102,09_GTvsRR,April 04,19:00:01,16,2,Kagiso Rabada,Ravindra Jadeja,1,0,0,N/A,0,0,Not Out,N/A,1
103,09_GTvsRR,April 04,19:00:01,16,3,Kagiso Rabada,Dhruv Jurel,6,0,0,N/A,0,0,Not Out,N/A,6
104,09_GTvsRR,April 04,19:00:01,16,4,Kagiso Rabada,Dhruv Jurel,0,1,1,wide,1,0,Not Out,N/A,1
105,09_GTvsRR,April 04,19:00:01,16,4,Kagiso Rabada,Dhruv Jurel,2,0,0,N/A,0,0,Not Out,N/A,2
106,09_GTvsRR,April 04,19:00:01,16,5,Kagiso Rabada,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
107,09_GTvsRR,April 04,19:00:01,16,6,Kagiso Rabada,Ravindra Jadeja,0,0,0,N/A,0,0,Not Out,N/A,0
108,09_GTvsRR,April 04,19:00:01,17,1,Ashok Sharma,Dhruv Jurel,6,0,0,N/A,0,0,Not Out,N/A,6
109,09_GTvsRR,April 04,19:00:01,17,2,Ashok Sharma,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
110,09_GTvsRR,April 04,19:00:01,17,3,Ashok Sharma,Ravindra Jadeja,1,0,0,N/A,0,0,Not Out,N/A,1
111,09_GTvsRR,April 04,19:00:01,17,4,Ashok Sharma,Dhruv Jurel,0,1,1,wide,1,0,Not Out,N/A,1
112,09_GTvsRR,April 04,19:00:01,17,4,Ashok Sharma,Dhruv Jurel,2,0,0,N/A,0,0,Not Out,N/A,2
113,09_GTvsRR,April 04,19:00:01,17,5,Ashok Sharma,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
114,09_GTvsRR,April 04,19:00:01,17,6,Ashok Sharma,Ravindra Jadeja,0,1,1,wide,1,0,Not Out,N/A,1
115,09_GTvsRR,April 04,19:00:01,17,6,Ashok Sharma,Ravindra Jadeja,0,0,0,N/A,0,0,Not Out,N/A,0
116,09_GTvsRR,April 04,19:00:01,18,1,Prasidh Krishna,Dhruv Jurel,2,0,0,N/A,0,0,Not Out,N/A,2
117,09_GTvsRR,April 04,19:00:01,18,2,Prasidh Krishna,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
118,09_GTvsRR,April 04,19:00:01,18,3,Prasidh Krishna,Ravindra Jadeja,1,0,0,N/A,0,0,Not Out,N/A,1
119,09_GTvsRR,April 04,19:00:01,18,4,Prasidh Krishna,Dhruv Jurel,6,0,0,N/A,0,0,Not Out,N/A,6
120,09_GTvsRR,April 04,19:00:01,18,5,Prasidh Krishna,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1
121,09_GTvsRR,April 04,19:00:01,18,6,Prasidh Krishna,Ravindra Jadeja,0,0,0,N/A,0,0,Not Out,N/A,0
122,09_GTvsRR,April 04,19:00:01,19,1,Mohammed Siraj,Dhruv Jurel,4,0,0,N/A,0,0,Not Out,N/A,4
123,09_GTvsRR,April 04,19:00:01,19,2,Mohammed Siraj,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0
124,09_GTvsRR,April 04,19:00:01,19,3,Mohammed Siraj,Dhruv Jurel,0,0,0,N/A,0,1,Caught,Dhruv Jurel,0
125,09_GTvsRR,April 04,19:00:01,19,4,Mohammed Siraj,Jofra Archer,0,0,0,N/A,0,0,Not Out,N/A,0
126,09_GTvsRR,April 04,19:00:01,19,5,Mohammed Siraj,Jofra Archer,1,0,0,N/A,0,0,Not Out,N/A,1
127,09_GTvsRR,April 04,19:00:01,19,6,Mohammed Siraj,Ravindra Jadeja,4,0,0,N/A,0,0,Not Out,N/A,4
128,09_GTvsRR,April 04,19:00:01,0,1,Jofra Archer,Sai Sudharsan,4,1,1,wide,1,0,Not Out,N/A,5
129,09_GTvsRR,April 04,19:00:01,0,1,Jofra Archer,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0
130,09_GTvsRR,April 04,19:00:01,0,2,Jofra Archer,Sai Sudharsan,6,0,0,N/A,0,0,Not Out,N/A,6
131,09_GTvsRR,April 04,19:00:01,0,3,Jofra Archer,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0
132,09_GTvsRR,April 04,19:00:01,0,4,Jofra Archer,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0
133,09_GTvsRR,April 04,19:00:01,0,5,Jofra Archer,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0
134,09_GTvsRR,April 04,19:00:01,0,6,Jofra Archer,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4
135,09_GTvsRR,April 04,19:00:01,1,1,Nandre Burger,Kumar Kushagra,1,0,0,N/A,0,0,Not Out,N/A,1
136,09_GTvsRR,April 04,19:00:01,1,2,Nandre Burger,Sai Sudharsan,0,1,1,wide,1,0,Not Out,N/A,1
137,09_GTvsRR,April 04,19:00:01,1,2,Nandre Burger,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4
138,09_GTvsRR,April 04,19:00:01,1,3,Nandre Burger,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0
139,09_GTvsRR,April 04,19:00:01,1,4,Nandre Burger,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1
140,09_GTvsRR,April 04,19:00:01,1,5,Nandre Burger,Kumar Kushagra,0,0,0,N/A,0,0,Not Out,N/A,0
141,09_GTvsRR,April 04,19:00:01,1,6,Nandre Burger,Kumar Kushagra,0,0,0,N/A,0,0,Not Out,N/A,0
142,09_GTvsRR,April 04,19:00:01,2,1,Jofra Archer,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0
143,09_GTvsRR,April 04,19:00:01,2,2,Jofra Archer,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1
144,09_GTvsRR,April 04,19:00:01,2,3,Jofra Archer,Kumar Kushagra,4,0,0,N/A,0,0,Not Out,N/A,4
145,09_GTvsRR,April 04,19:00:01,2,4,Jofra Archer,Kumar Kushagra,0,0,0,N/A,0,0,Not Out,N/A,0
146,09_GTvsRR,April 04,19:00:01,2,5,Jofra Archer,Kumar Kushagra,1,0,0,N/A,0,0,Not Out,N/A,1
147,09_GTvsRR,April 04,19:00:01,2,6,Jofra Archer,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4
148,09_GTvsRR,April 04,19:00:01,3,1,Sandeep Sharma,Kumar Kushagra,2,0,0,N/A,0,0,Not Out,N/A,2
149,09_GTvsRR,April 04,19:00:01,3,2,Sandeep Sharma,Kumar Kushagra,4,0,0,N/A,0,0,Not Out,N/A,4
150,09_GTvsRR,April 04,19:00:01,3,3,Sandeep Sharma,Kumar Kushagra,1,0,0,N/A,0,0,Not Out,N/A,1
151,09_GTvsRR,April 04,19:00:01,3,4,Sandeep Sharma,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0
152,09_GTvsRR,April 04,19:00:01,3,5,Sandeep Sharma,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0
153,09_GTvsRR,April 04,19:00:01,3,6,Sandeep Sharma,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1
154,09_GTvsRR,April 04,19:00:01,4,1,Tushar Deshpande,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4
155,09_GTvsRR,April 04,19:00:01,4,2,Tushar Deshpande,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0
156,09_GTvsRR,April 04,19:00:01,4,3,Tushar Deshpande,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0
157,09_GTvsRR,April 04,19:00:01,4,4,Tushar Deshpande,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0
158,09_GTvsRR,April 04,19:00:01,4,5,Tushar Deshpande,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0
159,09_GTvsRR,April 04,19:00:01,4,6,Tushar Deshpande,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1
160,09_GTvsRR,April 04,19:00:01,5,1,Sandeep Sharma,Sai Sudharsan,2,0,0,N/A,0,0,Not Out,N/A,2
161,09_GTvsRR,April 04,19:00:01,5,2,Sandeep Sharma,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4
162,09_GTvsRR,April 04,19:00:01,5,3,Sandeep Sharma,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1
163,09_GTvsRR,April 04,19:00:01,5,4,Sandeep Sharma,Kumar Kushagra,4,0,0,N/A,0,0,Not Out,N/A,4
164,09_GTvsRR,April 04,19:00:01,5,5,Sandeep Sharma,Kumar Kushagra,0,0,0,N/A,0,0,Not Out,N/A,0
165,09_GTvsRR,April 04,19:00:01,5,6,Sandeep Sharma,Kumar Kushagra,0,0,0,N/A,0,0,Not Out,N/A,0
166,09_GTvsRR,April 04,19:00:01,6,1,Ravindra Jadeja,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4
167,09_GTvsRR,April 04,19:00:01,6,2,Ravindra Jadeja,Sai Sudharsan,2,0,0,N/A,0,0,Not Out,N/A,2
168,09_GTvsRR,April 04,19:00:01,6,3,Ravindra Jadeja,Sai Sudharsan,2,0,0,N/A,0,0,Not Out,N/A,2
169,09_GTvsRR,April 04,19:00:01,6,4,Ravindra Jadeja,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1
170,09_GTvsRR,April 04,19:00:01,6,5,Ravindra Jadeja,Kumar Kushagra,1,0,0,N/A,0,0,Not Out,N/A,1
171,09_GTvsRR,April 04,19:00:01,6,6,Ravindra Jadeja,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1
172,09_GTvsRR,April 04,19:00:01,7,1,Riyan Parag,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4
173,09_GTvsRR,April 04,19:00:01,7,3,Riyan Parag,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0
174,09_GTvsRR,April 04,19:00:01,7,4,Riyan Parag,Sai Sudharsan,6,0,0,N/A,0,0,Not Out,N/A,6
175,09_GTvsRR,April 04,19:00:01,7,5,Riyan Parag,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1
176,09_GTvsRR,April 04,19:00:01,7,6,Riyan Parag,Kumar Kushagra,0,0,0,N/A,0,1,Caught,Kumar Kushagra,0
177,09_GTvsRR,April 04,19:00:01,8,2,Ravindra Jadeja,Jos Buttler,1,0,0,N/A,0,0,Not Out,N/A,1
178,09_GTvsRR,April 04,19:00:01,8,3,Ravindra Jadeja,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4
179,09_GTvsRR,April 04,19:00:01,8,4,Ravindra Jadeja,Sai Sudharsan,2,0,0,N/A,0,0,Not Out,N/A,2
180,09_GTvsRR,April 04,19:00:01,8,5,Ravindra Jadeja,Sai Sudharsan,6,0,0,N/A,0,0,Not Out,N/A,6
181,09_GTvsRR,April 04,19:00:01,8,6,Ravindra Jadeja,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0
182,09_GTvsRR,April 04,19:00:01,9,1,Nandre Burger,Jos Buttler,1,0,1,leg byes,0,0,Not Out,N/A,1
183,09_GTvsRR,April 04,19:00:01,9,2,Nandre Burger,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1
184,09_GTvsRR,April 04,19:00:01,9,3,Nandre Burger,Jos Buttler,4,0,0,N/A,0,0,Not Out,N/A,4
185,09_GTvsRR,April 04,19:00:01,9,4,Nandre Burger,Jos Buttler,0,0,0,N/A,0,0,Not Out,N/A,0
186,09_GTvsRR,April 04,19:00:01,9,5,Nandre Burger,Jos Buttler,1,0,0,N/A,0,0,Not Out,N/A,1
187,09_GTvsRR,April 04,19:00:01,9,6,Nandre Burger,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4
188,09_GTvsRR,April 04,19:00:01,10,1,Ravi Bishnoi,Jos Buttler,1,0,0,N/A,0,0,Not Out,N/A,1
189,09_GTvsRR,April 04,19:00:01,10,2,Ravi Bishnoi,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1
190,09_GTvsRR,April 04,19:00:01,10,2,Ravi Bishnoi,Sai Sudharsan,1,1,1,no ball,1,0,Not Out,N/A,2
191,09_GTvsRR,April 04,19:00:01,10,2,Ravi Bishnoi,Jos Buttler,1,0,0,N/A,0,0,Not Out,N/A,1
192,09_GTvsRR,April 04,19:00:01,10,3,Ravi Bishnoi,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0
193,09_GTvsRR,April 04,19:00:01,10,4,Ravi Bishnoi,Sai Sudharsan,0,0,0,N/A,0,1,Caught,Sai Sudharsan,0
194,09_GTvsRR,April 04,19:00:01,10,5,Ravi Bishnoi,Glenn Phillips,1,0,0,N/A,0,0,Not Out,N/A,1
195,09_GTvsRR,April 04,19:00:01,10,6,Ravi Bishnoi,Jos Buttler,4,0,0,N/A,0,0,Not Out,N/A,4
196,09_GTvsRR,April 04,19:00:01,11,1,Tushar Deshpande,Glenn Phillips,1,0,0,N/A,0,0,Not Out,N/A,1
197,09_GTvsRR,April 04,19:00:01,11,2,Tushar Deshpande,Jos Buttler,4,0,0,N/A,0,0,Not Out,N/A,4
198,09_GTvsRR,April 04,19:00:01,11,3,Tushar Deshpande,Jos Buttler,1,0,0,N/A,0,0,Not Out,N/A,1
199,09_GTvsRR,April 04,19:00:01,11,4,Tushar Deshpande,Glenn Phillips,1,0,0,N/A,0,0,Not Out,N/A,1
200,09_GTvsRR,April 04,19:00:01,11,5,Tushar Deshpande,Jos Buttler,4,0,0,N/A,0,0,Not Out,N/A,4
201,09_GTvsRR,April 04,19:00:01,11,6,Tushar Deshpande,Jos Buttler,4,0,0,N/A,0,0,Not Out,N/A,4
202,09_GTvsRR,April 04,19:00:01,12,1,Ravi Bishnoi,Glenn Phillips,0,0,0,N/A,0,1,Caught,Glenn Phillips,0
203,09_GTvsRR,April 04,19:00:01,12,2,Ravi Bishnoi,Washington Sundar,4,0,0,N/A,0,0,Not Out,N/A,4
204,09_GTvsRR,April 04,19:00:01,12,3,Ravi Bishnoi,Washington Sundar,0,0,0,N/A,0,1,Caught,Washington Sundar,0
205,09_GTvsRR,April 04,19:00:01,12,4,Ravi Bishnoi,Rahul Tewatia,0,0,0,N/A,0,0,Not Out,N/A,0
206,09_GTvsRR,April 04,19:00:01,12,5,Ravi Bishnoi,Rahul Tewatia,1,0,0,N/A,0,0,Not Out,N/A,1
207,09_GTvsRR,April 04,19:00:01,12,6,Ravi Bishnoi,Jos Buttler,1,0,0,N/A,0,0,Not Out,N/A,1
208,09_GTvsRR,April 04,19:00:01,13,1,Nandre Burger,Jos Buttler,0,0,0,N/A,0,1,Caught,Jos Buttler,0
209,09_GTvsRR,April 04,19:00:01,13,2,Nandre Burger,Shahrukh Khan,1,0,0,N/A,0,0,Not Out,N/A,1
210,09_GTvsRR,April 04,19:00:01,13,3,Nandre Burger,Rahul Tewatia,1,0,0,N/A,0,0,Not Out,N/A,1
211,09_GTvsRR,April 04,19:00:01,13,4,Nandre Burger,Shahrukh Khan,6,0,0,N/A,0,0,Not Out,N/A,6

In [52]:
final = []

for index, row in df2.iterrows():

    row_dict = row.to_dict()

    if final == []:
        row_dict['innings'] = 1
        row_dict['score'] = row_dict['total_runs']
        row_dict['fallen_wickets'] = row_dict['wicket']

    else:
        prev_ball_innings = int(final[-1]['innings'])
        if row_dict['over'] == 0 and row_dict['ball'] == 1:
            if final[-1]['rebowl'] == 0:
                row_dict['innings'] = prev_ball_innings + 1 
                row_dict['score'] = 0
                row_dict['fallen_wickets'] = 0  
            else: row_dict['innings'] = prev_ball_innings
        else: row_dict['innings'] = prev_ball_innings        

        if row_dict['innings'] == prev_ball_innings:
            row_dict['score'] = final[-1]['score'] + row_dict['total_runs']
            row_dict['fallen_wickets'] = final[-1]['fallen_wickets'] + row_dict['wicket']
        else:
            row_dict['score'] = 0
            row_dict['fallen_wickets'] = 0

    final.append(row_dict)

In [53]:
pd.DataFrame(final)

,match,data,time,over,ball,bowler,batsman,runs,extra_runs,extra,extra_type,rebowl,wicket,wicket_method,out_batsman,total_runs,innings,score,fallen_wickets
0,09_GTvsRR,April 04,19:00:01,0,1,Mohammed Siraj,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1,1,1,0
1,09_GTvsRR,April 04,19:00:01,0,2,Mohammed Siraj,Vaibhav Sooryavanshi,4,0,0,N/A,0,0,Not Out,N/A,4,1,5,0
2,09_GTvsRR,April 04,19:00:01,0,3,Mohammed Siraj,Vaibhav Sooryavanshi,0,0,0,N/A,0,0,Not Out,N/A,0,1,5,0
3,09_GTvsRR,April 04,19:00:01,0,4,Mohammed Siraj,Vaibhav Sooryavanshi,4,0,0,N/A,0,0,Not Out,N/A,4,1,9,0
4,09_GTvsRR,April 04,19:00:01,0,5,Mohammed Siraj,Vaibhav Sooryavanshi,1,0,0,N/A,0,0,Not Out,N/A,1,1,10,0
5,09_GTvsRR,April 04,19:00:01,0,6,Mohammed Siraj,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0,1,10,0
6,09_GTvsRR,April 04,19:00:01,1,1,Kagiso Rabada,Vaibhav Sooryavanshi,1,0,0,N/A,0,0,Not Out,N/A,1,1,11,0
7,09_GTvsRR,April 04,19:00:01,1,2,Kagiso Rabada,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1,1,12,0
8,09_GTvsRR,April 04,19:00:01,1,3,Kagiso Rabada,Vaibhav Sooryavanshi,0,0,0,N/A,0,0,Not Out,N/A,0,1,12,0
9,09_GTvsRR,April 04,19:00:01,1,4,Kagiso Rabada,Vaibhav Sooryavanshi,0,1,1,wide,1,0,Not Out,N/A,1,1,13,0
10,09_GTvsRR,April 04,19:00:01,1,4,Kagiso Rabada,Vaibhav Sooryavanshi,0,0,0,N/A,0,0,Not Out,N/A,0,1,13,0
11,09_GTvsRR,April 04,19:00:01,1,5,Kagiso Rabada,Vaibhav Sooryavanshi,4,0,0,N/A,0,0,Not Out,N/A,4,1,17,0
12,09_GTvsRR,April 04,19:00:01,1,6,Kagiso Rabada,Vaibhav Sooryavanshi,0,0,0,N/A,0,0,Not Out,N/A,0,1,17,0
13,09_GTvsRR,April 04,19:00:01,2,1,Mohammed Siraj,Yashasvi Jaiswal,6,0,0,N/A,0,0,Not Out,N/A,6,1,23,0
14,09_GTvsRR,April 04,19:00:01,2,2,Mohammed Siraj,Yashasvi Jaiswal,4,0,0,N/A,0,0,Not Out,N/A,4,1,27,0
15,09_GTvsRR,April 04,19:00:01,2,3,Mohammed Siraj,Yashasvi Jaiswal,0,1,1,wide,1,0,Not Out,N/A,1,1,28,0
16,09_GTvsRR,April 04,19:00:01,2,3,Mohammed Siraj,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0,1,28,0
17,09_GTvsRR,April 04,19:00:01,2,4,Mohammed Siraj,Yashasvi Jaiswal,4,0,0,N/A,0,0,Not Out,N/A,4,1,32,0
18,09_GTvsRR,April 04,19:00:01,2,5,Mohammed Siraj,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0,1,32,0
19,09_GTvsRR,April 04,19:00:01,2,6,Mohammed Siraj,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0,1,32,0
20,09_GTvsRR,April 04,19:00:01,3,1,Kagiso Rabada,Vaibhav Sooryavanshi,0,0,0,N/A,0,0,Not Out,N/A,0,1,32,0
21,09_GTvsRR,April 04,19:00:01,3,2,Kagiso Rabada,Vaibhav Sooryavanshi,0,1,1,wide,1,0,Not Out,N/A,1,1,33,0
22,09_GTvsRR,April 04,19:00:01,3,2,Kagiso Rabada,Vaibhav Sooryavanshi,4,0,0,N/A,0,0,Not Out,N/A,4,1,37,0
23,09_GTvsRR,April 04,19:00:01,3,3,Kagiso Rabada,Vaibhav Sooryavanshi,1,0,0,N/A,0,0,Not Out,N/A,1,1,38,0
24,09_GTvsRR,April 04,19:00:01,3,4,Kagiso Rabada,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0,1,38,0
25,09_GTvsRR,April 04,19:00:01,3,5,Kagiso Rabada,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0,1,38,0
26,09_GTvsRR,April 04,19:00:01,3,6,Kagiso Rabada,Yashasvi Jaiswal,6,0,0,N/A,0,0,Not Out,N/A,6,1,44,0
27,09_GTvsRR,April 04,19:00:01,4,1,Ashok Sharma,Vaibhav Sooryavanshi,4,0,0,N/A,0,0,Not Out,N/A,4,1,48,0
28,09_GTvsRR,April 04,19:00:01,4,2,Ashok Sharma,Vaibhav Sooryavanshi,6,0,0,N/A,0,0,Not Out,N/A,6,1,54,0
29,09_GTvsRR,April 04,19:00:01,4,3,Ashok Sharma,Vaibhav Sooryavanshi,1,0,0,N/A,0,0,Not Out,N/A,1,1,55,0
30,09_GTvsRR,April 04,19:00:01,4,4,Ashok Sharma,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0,1,55,0
31,09_GTvsRR,April 04,19:00:01,4,5,Ashok Sharma,Yashasvi Jaiswal,2,0,0,N/A,0,0,Not Out,N/A,2,1,57,0
32,09_GTvsRR,April 04,19:00:01,4,6,Ashok Sharma,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0,1,57,0
33,09_GTvsRR,April 04,19:00:01,5,1,Prasidh Krishna,Vaibhav Sooryavanshi,1,0,0,N/A,0,0,Not Out,N/A,1,1,58,0
34,09_GTvsRR,April 04,19:00:01,5,2,Prasidh Krishna,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0,1,58,0
35,09_GTvsRR,April 04,19:00:01,5,3,Prasidh Krishna,Yashasvi Jaiswal,6,0,0,N/A,0,0,Not Out,N/A,6,1,64,0
36,09_GTvsRR,April 04,19:00:01,5,4,Prasidh Krishna,Yashasvi Jaiswal,4,0,0,N/A,0,0,Not Out,N/A,4,1,68,0
37,09_GTvsRR,April 04,19:00:01,5,5,Prasidh Krishna,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1,1,69,0
38,09_GTvsRR,April 04,19:00:01,5,6,Prasidh Krishna,Vaibhav Sooryavanshi,0,0,0,N/A,0,0,Not Out,N/A,0,1,69,0
39,09_GTvsRR,April 04,19:00:01,6,1,Rashid Khan,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1,1,70,0
40,09_GTvsRR,April 04,19:00:01,6,2,Rashid Khan,Vaibhav Sooryavanshi,0,0,0,N/A,0,1,Caught,Vaibhav Sooryavanshi,0,1,70,1
41,09_GTvsRR,April 04,19:00:01,6,3,Rashid Khan,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,71,1
42,09_GTvsRR,April 04,19:00:01,6,4,Rashid Khan,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1,1,72,1
43,09_GTvsRR,April 04,19:00:01,6,5,Rashid Khan,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,73,1
44,09_GTvsRR,April 04,19:00:01,6,6,Rashid Khan,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1,1,74,1
45,09_GTvsRR,April 04,19:00:01,7,1,Prasidh Krishna,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0,1,74,1
46,09_GTvsRR,April 04,19:00:01,7,2,Prasidh Krishna,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0,1,74,1
47,09_GTvsRR,April 04,19:00:01,7,3,Prasidh Krishna,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1,1,75,1
48,09_GTvsRR,April 04,19:00:01,7,4,Prasidh Krishna,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0,1,75,1
49,09_GTvsRR,April 04,19:00:01,7,5,Prasidh Krishna,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,76,1
50,09_GTvsRR,April 04,19:00:01,7,6,Prasidh Krishna,Yashasvi Jaiswal,4,0,0,N/A,0,0,Not Out,N/A,4,1,80,1
51,09_GTvsRR,April 04,19:00:01,8,1,Rashid Khan,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,81,1
52,09_GTvsRR,April 04,19:00:01,8,2,Rashid Khan,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1,1,82,1
53,09_GTvsRR,April 04,19:00:01,8,3,Rashid Khan,Dhruv Jurel,4,1,1,wide,1,0,Not Out,N/A,5,1,87,1
54,09_GTvsRR,April 04,19:00:01,8,3,Rashid Khan,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,88,1
55,09_GTvsRR,April 04,19:00:01,8,4,Rashid Khan,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1,1,89,1
56,09_GTvsRR,April 04,19:00:01,8,5,Rashid Khan,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,90,1
57,09_GTvsRR,April 04,19:00:01,8,6,Rashid Khan,Yashasvi Jaiswal,2,0,0,N/A,0,0,Not Out,N/A,2,1,92,1
58,09_GTvsRR,April 04,19:00:01,9,1,Ashok Sharma,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0,1,92,1
59,09_GTvsRR,April 04,19:00:01,9,2,Ashok Sharma,Dhruv Jurel,4,0,0,N/A,0,0,Not Out,N/A,4,1,96,1
60,09_GTvsRR,April 04,19:00:01,9,3,Ashok Sharma,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0,1,96,1
61,09_GTvsRR,April 04,19:00:01,9,4,Ashok Sharma,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0,1,96,1
62,09_GTvsRR,April 04,19:00:01,9,5,Ashok Sharma,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,97,1
63,09_GTvsRR,April 04,19:00:01,9,6,Ashok Sharma,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0,1,97,1
64,09_GTvsRR,April 04,19:00:01,10,1,Rashid Khan,Dhruv Jurel,4,0,0,N/A,0,0,Not Out,N/A,4,1,101,1
65,09_GTvsRR,April 04,19:00:01,10,2,Rashid Khan,Dhruv Jurel,2,0,0,N/A,0,0,Not Out,N/A,2,1,103,1
66,09_GTvsRR,April 04,19:00:01,10,3,Rashid Khan,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0,1,103,1
67,09_GTvsRR,April 04,19:00:01,10,5,Rashid Khan,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0,1,103,1
68,09_GTvsRR,April 04,19:00:01,10,6,Rashid Khan,Dhruv Jurel,4,0,0,N/A,0,0,Not Out,N/A,4,1,107,1
69,09_GTvsRR,April 04,19:00:01,11,1,Mohammed Siraj,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0,1,107,1
70,09_GTvsRR,April 04,19:00:01,11,2,Mohammed Siraj,Yashasvi Jaiswal,4,0,0,N/A,0,0,Not Out,N/A,4,1,111,1
71,09_GTvsRR,April 04,19:00:01,11,3,Mohammed Siraj,Yashasvi Jaiswal,1,0,0,N/A,0,0,Not Out,N/A,1,1,112,1
72,09_GTvsRR,April 04,19:00:01,11,3,Mohammed Siraj,Yashasvi Jaiswal,1,0,1,leg byes,0,0,Not Out,N/A,1,1,113,1
73,09_GTvsRR,April 04,19:00:01,11,4,Mohammed Siraj,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0,1,113,1
74,09_GTvsRR,April 04,19:00:01,11,5,Mohammed Siraj,Dhruv Jurel,4,0,0,N/A,0,0,Not Out,N/A,4,1,117,1
75,09_GTvsRR,April 04,19:00:01,11,6,Mohammed Siraj,Dhruv Jurel,6,0,0,N/A,0,0,Not Out,N/A,6,1,123,1
76,09_GTvsRR,April 04,19:00:01,12,1,Kagiso Rabada,Yashasvi Jaiswal,0,0,0,N/A,0,0,Not Out,N/A,0,1,123,1
77,09_GTvsRR,April 04,19:00:01,12,2,Kagiso Rabada,Yashasvi Jaiswal,4,0,0,N/A,0,0,Not Out,N/A,4,1,127,1
78,09_GTvsRR,April 04,19:00:01,12,3,Kagiso Rabada,Yashasvi Jaiswal,0,0,0,N/A,0,1,Bowled!!,Yashasvi Jaiswal,0,1,127,2
79,09_GTvsRR,April 04,19:00:01,12,4,Kagiso Rabada,Riyan Parag,6,0,0,N/A,0,0,Not Out,N/A,6,1,133,2
80,09_GTvsRR,April 04,19:00:01,12,5,Kagiso Rabada,Riyan Parag,2,0,0,N/A,0,0,Not Out,N/A,2,1,135,2
81,09_GTvsRR,April 04,19:00:01,12,6,Kagiso Rabada,Riyan Parag,0,0,0,N/A,0,0,Not Out,N/A,0,1,135,2
82,09_GTvsRR,April 04,19:00:01,13,1,Prasidh Krishna,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,136,2
83,09_GTvsRR,April 04,19:00:01,13,2,Prasidh Krishna,Riyan Parag,0,0,0,N/A,0,1,Caught,Riyan Parag,0,1,136,3
84,09_GTvsRR,April 04,19:00:01,13,3,Prasidh Krishna,Shimron Hetmyer,0,0,0,N/A,0,0,Not Out,N/A,0,1,136,3
85,09_GTvsRR,April 04,19:00:01,13,4,Prasidh Krishna,Shimron Hetmyer,0,1,1,wide,1,0,Not Out,N/A,1,1,137,3
86,09_GTvsRR,April 04,19:00:01,13,4,Prasidh Krishna,Shimron Hetmyer,0,0,0,N/A,0,0,Not Out,N/A,0,1,137,3
87,09_GTvsRR,April 04,19:00:01,13,5,Prasidh Krishna,Shimron Hetmyer,6,0,0,N/A,0,0,Not Out,N/A,6,1,143,3
88,09_GTvsRR,April 04,19:00:01,13,6,Prasidh Krishna,Shimron Hetmyer,6,0,0,N/A,0,0,Not Out,N/A,6,1,149,3
89,09_GTvsRR,April 04,19:00:01,14,1,Rashid Khan,Dhruv Jurel,0,1,1,wide,1,0,Not Out,N/A,1,1,150,3
90,09_GTvsRR,April 04,19:00:01,14,1,Rashid Khan,Dhruv Jurel,6,0,0,N/A,0,0,Not Out,N/A,6,1,156,3
91,09_GTvsRR,April 04,19:00:01,14,3,Rashid Khan,Shimron Hetmyer,1,0,0,N/A,0,0,Not Out,N/A,1,1,157,3
92,09_GTvsRR,April 04,19:00:01,14,4,Rashid Khan,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,158,3
93,09_GTvsRR,April 04,19:00:01,14,5,Rashid Khan,Shimron Hetmyer,1,0,0,N/A,0,0,Not Out,N/A,1,1,159,3
94,09_GTvsRR,April 04,19:00:01,14,6,Rashid Khan,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,160,3
95,09_GTvsRR,April 04,19:00:01,15,1,Ashok Sharma,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,161,3
96,09_GTvsRR,April 04,19:00:01,15,2,Ashok Sharma,Shimron Hetmyer,4,0,0,N/A,0,0,Not Out,N/A,4,1,165,3
97,09_GTvsRR,April 04,19:00:01,15,3,Ashok Sharma,Shimron Hetmyer,0,0,0,N/A,0,1,Caught,Shimron Hetmyer,0,1,165,4
98,09_GTvsRR,April 04,19:00:01,15,4,Ashok Sharma,Donovan Ferreira,0,0,0,N/A,0,0,Not Out,N/A,0,1,165,4
99,09_GTvsRR,April 04,19:00:01,15,5,Ashok Sharma,Donovan Ferreira,1,0,0,N/A,0,0,Not Out,N/A,1,1,166,4
100,09_GTvsRR,April 04,19:00:01,15,6,Ashok Sharma,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0,1,166,4
101,09_GTvsRR,April 04,19:00:01,16,1,Kagiso Rabada,Donovan Ferreira,0,0,0,N/A,0,1,Caught,Donovan Ferreira,0,1,166,5
102,09_GTvsRR,April 04,19:00:01,16,2,Kagiso Rabada,Ravindra Jadeja,1,0,0,N/A,0,0,Not Out,N/A,1,1,167,5
103,09_GTvsRR,April 04,19:00:01,16,3,Kagiso Rabada,Dhruv Jurel,6,0,0,N/A,0,0,Not Out,N/A,6,1,173,5
104,09_GTvsRR,April 04,19:00:01,16,4,Kagiso Rabada,Dhruv Jurel,0,1,1,wide,1,0,Not Out,N/A,1,1,174,5
105,09_GTvsRR,April 04,19:00:01,16,4,Kagiso Rabada,Dhruv Jurel,2,0,0,N/A,0,0,Not Out,N/A,2,1,176,5
106,09_GTvsRR,April 04,19:00:01,16,5,Kagiso Rabada,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,177,5
107,09_GTvsRR,April 04,19:00:01,16,6,Kagiso Rabada,Ravindra Jadeja,0,0,0,N/A,0,0,Not Out,N/A,0,1,177,5
108,09_GTvsRR,April 04,19:00:01,17,1,Ashok Sharma,Dhruv Jurel,6,0,0,N/A,0,0,Not Out,N/A,6,1,183,5
109,09_GTvsRR,April 04,19:00:01,17,2,Ashok Sharma,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,184,5
110,09_GTvsRR,April 04,19:00:01,17,3,Ashok Sharma,Ravindra Jadeja,1,0,0,N/A,0,0,Not Out,N/A,1,1,185,5
111,09_GTvsRR,April 04,19:00:01,17,4,Ashok Sharma,Dhruv Jurel,0,1,1,wide,1,0,Not Out,N/A,1,1,186,5
112,09_GTvsRR,April 04,19:00:01,17,4,Ashok Sharma,Dhruv Jurel,2,0,0,N/A,0,0,Not Out,N/A,2,1,188,5
113,09_GTvsRR,April 04,19:00:01,17,5,Ashok Sharma,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,189,5
114,09_GTvsRR,April 04,19:00:01,17,6,Ashok Sharma,Ravindra Jadeja,0,1,1,wide,1,0,Not Out,N/A,1,1,190,5
115,09_GTvsRR,April 04,19:00:01,17,6,Ashok Sharma,Ravindra Jadeja,0,0,0,N/A,0,0,Not Out,N/A,0,1,190,5
116,09_GTvsRR,April 04,19:00:01,18,1,Prasidh Krishna,Dhruv Jurel,2,0,0,N/A,0,0,Not Out,N/A,2,1,192,5
117,09_GTvsRR,April 04,19:00:01,18,2,Prasidh Krishna,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,193,5
118,09_GTvsRR,April 04,19:00:01,18,3,Prasidh Krishna,Ravindra Jadeja,1,0,0,N/A,0,0,Not Out,N/A,1,1,194,5
119,09_GTvsRR,April 04,19:00:01,18,4,Prasidh Krishna,Dhruv Jurel,6,0,0,N/A,0,0,Not Out,N/A,6,1,200,5
120,09_GTvsRR,April 04,19:00:01,18,5,Prasidh Krishna,Dhruv Jurel,1,0,0,N/A,0,0,Not Out,N/A,1,1,201,5
121,09_GTvsRR,April 04,19:00:01,18,6,Prasidh Krishna,Ravindra Jadeja,0,0,0,N/A,0,0,Not Out,N/A,0,1,201,5
122,09_GTvsRR,April 04,19:00:01,19,1,Mohammed Siraj,Dhruv Jurel,4,0,0,N/A,0,0,Not Out,N/A,4,1,205,5
123,09_GTvsRR,April 04,19:00:01,19,2,Mohammed Siraj,Dhruv Jurel,0,0,0,N/A,0,0,Not Out,N/A,0,1,205,5
124,09_GTvsRR,April 04,19:00:01,19,3,Mohammed Siraj,Dhruv Jurel,0,0,0,N/A,0,1,Caught,Dhruv Jurel,0,1,205,6
125,09_GTvsRR,April 04,19:00:01,19,4,Mohammed Siraj,Jofra Archer,0,0,0,N/A,0,0,Not Out,N/A,0,1,205,6
126,09_GTvsRR,April 04,19:00:01,19,5,Mohammed Siraj,Jofra Archer,1,0,0,N/A,0,0,Not Out,N/A,1,1,206,6
127,09_GTvsRR,April 04,19:00:01,19,6,Mohammed Siraj,Ravindra Jadeja,4,0,0,N/A,0,0,Not Out,N/A,4,1,210,6
128,09_GTvsRR,April 04,19:00:01,0,1,Jofra Archer,Sai Sudharsan,4,1,1,wide,1,0,Not Out,N/A,5,2,0,0
129,09_GTvsRR,April 04,19:00:01,0,1,Jofra Archer,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0,2,0,0
130,09_GTvsRR,April 04,19:00:01,0,2,Jofra Archer,Sai Sudharsan,6,0,0,N/A,0,0,Not Out,N/A,6,2,6,0
131,09_GTvsRR,April 04,19:00:01,0,3,Jofra Archer,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0,2,6,0
132,09_GTvsRR,April 04,19:00:01,0,4,Jofra Archer,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0,2,6,0
133,09_GTvsRR,April 04,19:00:01,0,5,Jofra Archer,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0,2,6,0
134,09_GTvsRR,April 04,19:00:01,0,6,Jofra Archer,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4,2,10,0
135,09_GTvsRR,April 04,19:00:01,1,1,Nandre Burger,Kumar Kushagra,1,0,0,N/A,0,0,Not Out,N/A,1,2,11,0
136,09_GTvsRR,April 04,19:00:01,1,2,Nandre Burger,Sai Sudharsan,0,1,1,wide,1,0,Not Out,N/A,1,2,12,0
137,09_GTvsRR,April 04,19:00:01,1,2,Nandre Burger,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4,2,16,0
138,09_GTvsRR,April 04,19:00:01,1,3,Nandre Burger,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0,2,16,0
139,09_GTvsRR,April 04,19:00:01,1,4,Nandre Burger,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1,2,17,0
140,09_GTvsRR,April 04,19:00:01,1,5,Nandre Burger,Kumar Kushagra,0,0,0,N/A,0,0,Not Out,N/A,0,2,17,0
141,09_GTvsRR,April 04,19:00:01,1,6,Nandre Burger,Kumar Kushagra,0,0,0,N/A,0,0,Not Out,N/A,0,2,17,0
142,09_GTvsRR,April 04,19:00:01,2,1,Jofra Archer,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0,2,17,0
143,09_GTvsRR,April 04,19:00:01,2,2,Jofra Archer,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1,2,18,0
144,09_GTvsRR,April 04,19:00:01,2,3,Jofra Archer,Kumar Kushagra,4,0,0,N/A,0,0,Not Out,N/A,4,2,22,0
145,09_GTvsRR,April 04,19:00:01,2,4,Jofra Archer,Kumar Kushagra,0,0,0,N/A,0,0,Not Out,N/A,0,2,22,0
146,09_GTvsRR,April 04,19:00:01,2,5,Jofra Archer,Kumar Kushagra,1,0,0,N/A,0,0,Not Out,N/A,1,2,23,0
147,09_GTvsRR,April 04,19:00:01,2,6,Jofra Archer,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4,2,27,0
148,09_GTvsRR,April 04,19:00:01,3,1,Sandeep Sharma,Kumar Kushagra,2,0,0,N/A,0,0,Not Out,N/A,2,2,29,0
149,09_GTvsRR,April 04,19:00:01,3,2,Sandeep Sharma,Kumar Kushagra,4,0,0,N/A,0,0,Not Out,N/A,4,2,33,0
150,09_GTvsRR,April 04,19:00:01,3,3,Sandeep Sharma,Kumar Kushagra,1,0,0,N/A,0,0,Not Out,N/A,1,2,34,0
151,09_GTvsRR,April 04,19:00:01,3,4,Sandeep Sharma,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0,2,34,0
152,09_GTvsRR,April 04,19:00:01,3,5,Sandeep Sharma,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0,2,34,0
153,09_GTvsRR,April 04,19:00:01,3,6,Sandeep Sharma,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1,2,35,0
154,09_GTvsRR,April 04,19:00:01,4,1,Tushar Deshpande,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4,2,39,0
155,09_GTvsRR,April 04,19:00:01,4,2,Tushar Deshpande,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0,2,39,0
156,09_GTvsRR,April 04,19:00:01,4,3,Tushar Deshpande,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0,2,39,0
157,09_GTvsRR,April 04,19:00:01,4,4,Tushar Deshpande,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0,2,39,0
158,09_GTvsRR,April 04,19:00:01,4,5,Tushar Deshpande,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0,2,39,0
159,09_GTvsRR,April 04,19:00:01,4,6,Tushar Deshpande,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1,2,40,0
160,09_GTvsRR,April 04,19:00:01,5,1,Sandeep Sharma,Sai Sudharsan,2,0,0,N/A,0,0,Not Out,N/A,2,2,42,0
161,09_GTvsRR,April 04,19:00:01,5,2,Sandeep Sharma,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4,2,46,0
162,09_GTvsRR,April 04,19:00:01,5,3,Sandeep Sharma,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1,2,47,0
163,09_GTvsRR,April 04,19:00:01,5,4,Sandeep Sharma,Kumar Kushagra,4,0,0,N/A,0,0,Not Out,N/A,4,2,51,0
164,09_GTvsRR,April 04,19:00:01,5,5,Sandeep Sharma,Kumar Kushagra,0,0,0,N/A,0,0,Not Out,N/A,0,2,51,0
165,09_GTvsRR,April 04,19:00:01,5,6,Sandeep Sharma,Kumar Kushagra,0,0,0,N/A,0,0,Not Out,N/A,0,2,51,0
166,09_GTvsRR,April 04,19:00:01,6,1,Ravindra Jadeja,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4,2,55,0
167,09_GTvsRR,April 04,19:00:01,6,2,Ravindra Jadeja,Sai Sudharsan,2,0,0,N/A,0,0,Not Out,N/A,2,2,57,0
168,09_GTvsRR,April 04,19:00:01,6,3,Ravindra Jadeja,Sai Sudharsan,2,0,0,N/A,0,0,Not Out,N/A,2,2,59,0
169,09_GTvsRR,April 04,19:00:01,6,4,Ravindra Jadeja,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1,2,60,0
170,09_GTvsRR,April 04,19:00:01,6,5,Ravindra Jadeja,Kumar Kushagra,1,0,0,N/A,0,0,Not Out,N/A,1,2,61,0
171,09_GTvsRR,April 04,19:00:01,6,6,Ravindra Jadeja,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1,2,62,0
172,09_GTvsRR,April 04,19:00:01,7,1,Riyan Parag,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4,2,66,0
173,09_GTvsRR,April 04,19:00:01,7,3,Riyan Parag,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0,2,66,0
174,09_GTvsRR,April 04,19:00:01,7,4,Riyan Parag,Sai Sudharsan,6,0,0,N/A,0,0,Not Out,N/A,6,2,72,0
175,09_GTvsRR,April 04,19:00:01,7,5,Riyan Parag,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1,2,73,0
176,09_GTvsRR,April 04,19:00:01,7,6,Riyan Parag,Kumar Kushagra,0,0,0,N/A,0,1,Caught,Kumar Kushagra,0,2,73,1
177,09_GTvsRR,April 04,19:00:01,8,2,Ravindra Jadeja,Jos Buttler,1,0,0,N/A,0,0,Not Out,N/A,1,2,74,1
178,09_GTvsRR,April 04,19:00:01,8,3,Ravindra Jadeja,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4,2,78,1
179,09_GTvsRR,April 04,19:00:01,8,4,Ravindra Jadeja,Sai Sudharsan,2,0,0,N/A,0,0,Not Out,N/A,2,2,80,1
180,09_GTvsRR,April 04,19:00:01,8,5,Ravindra Jadeja,Sai Sudharsan,6,0,0,N/A,0,0,Not Out,N/A,6,2,86,1
181,09_GTvsRR,April 04,19:00:01,8,6,Ravindra Jadeja,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0,2,86,1
182,09_GTvsRR,April 04,19:00:01,9,1,Nandre Burger,Jos Buttler,1,0,1,leg byes,0,0,Not Out,N/A,1,2,87,1
183,09_GTvsRR,April 04,19:00:01,9,2,Nandre Burger,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1,2,88,1
184,09_GTvsRR,April 04,19:00:01,9,3,Nandre Burger,Jos Buttler,4,0,0,N/A,0,0,Not Out,N/A,4,2,92,1
185,09_GTvsRR,April 04,19:00:01,9,4,Nandre Burger,Jos Buttler,0,0,0,N/A,0,0,Not Out,N/A,0,2,92,1
186,09_GTvsRR,April 04,19:00:01,9,5,Nandre Burger,Jos Buttler,1,0,0,N/A,0,0,Not Out,N/A,1,2,93,1
187,09_GTvsRR,April 04,19:00:01,9,6,Nandre Burger,Sai Sudharsan,4,0,0,N/A,0,0,Not Out,N/A,4,2,97,1
188,09_GTvsRR,April 04,19:00:01,10,1,Ravi Bishnoi,Jos Buttler,1,0,0,N/A,0,0,Not Out,N/A,1,2,98,1
189,09_GTvsRR,April 04,19:00:01,10,2,Ravi Bishnoi,Sai Sudharsan,1,0,0,N/A,0,0,Not Out,N/A,1,2,99,1
190,09_GTvsRR,April 04,19:00:01,10,2,Ravi Bishnoi,Sai Sudharsan,1,1,1,no ball,1,0,Not Out,N/A,2,2,101,1
191,09_GTvsRR,April 04,19:00:01,10,2,Ravi Bishnoi,Jos Buttler,1,0,0,N/A,0,0,Not Out,N/A,1,2,102,1
192,09_GTvsRR,April 04,19:00:01,10,3,Ravi Bishnoi,Sai Sudharsan,0,0,0,N/A,0,0,Not Out,N/A,0,2,102,1
193,09_GTvsRR,April 04,19:00:01,10,4,Ravi Bishnoi,Sai Sudharsan,0,0,0,N/A,0,1,Caught,Sai Sudharsan,0,2,102,2
194,09_GTvsRR,April 04,19:00:01,10,5,Ravi Bishnoi,Glenn Phillips,1,0,0,N/A,0,0,Not Out,N/A,1,2,103,2
195,09_GTvsRR,April 04,19:00:01,10,6,Ravi Bishnoi,Jos Buttler,4,0,0,N/A,0,0,Not Out,N/A,4,2,107,2

In [7]:
df = pd.read_json("/home/rakshith/Data/IPL-2026/data/10_SHvsLSG/10_SHvsLSG_silver.json")
df.head(500)

,match,data,time,over,ball,bowler,batsman,runs,extra_runs,extra,extra_type,rebowl,wicket,wicket_method,out_batsman,total_runs,innings,score,fallen_wickets
0,10_SHvsLSG,April 05,15:30:02,0,1,Mohammed Shami,Travis Head,0,0,0,N/A,0,0,Not Out,N/A,0,1,0,0
1,10_SHvsLSG,April 05,15:30:02,0,2,Mohammed Shami,Travis Head,0,0,0,N/A,0,0,Not Out,N/A,0,1,0,0
2,10_SHvsLSG,April 05,15:30:02,0,3,Mohammed Shami,Travis Head,0,0,0,N/A,0,0,Not Out,N/A,0,1,0,0
3,10_SHvsLSG,April 05,15:30:02,0,3,Mohammed Shami,Travis Head,0,0,0,N/A,0,0,Not Out,N/A,0,1,0,0
4,10_SHvsLSG,April 05,15:30:02,0,4,Mohammed Shami,Travis Head,1,0,0,N/A,0,0,Not Out,N/A,1,1,1,0
5,10_SHvsLSG,April 05,15:30:02,0,4,Mohammed Shami,Travis Head,1,0,0,N/A,0,0,Not Out,N/A,1,1,2,0
6,10_SHvsLSG,April 05,15:30:02,0,5,Mohammed Shami,Abhishek Sharma,0,0,0,N/A,0,0,Not Out,N/A,0,1,2,0
7,10_SHvsLSG,April 05,15:30:02,0,4,Mohammed Shami,Travis Head,1,0,0,N/A,0,0,Not Out,N/A,1,1,3,0
8,10_SHvsLSG,April 05,15:30:02,0,5,Mohammed Shami,Abhishek Sharma,0,0,0,N/A,0,0,Not Out,N/A,0,1,3,0
9,10_SHvsLSG,April 05,15:30:02,0,5,Mohammed Shami,Abhishek Sharma,0,0,0,N/A,0,0,Not Out,N/A,0,1,3,0
10,10_SHvsLSG,April 05,15:30:02,0,6,Mohammed Shami,Abhishek Sharma,0,0,0,N/A,0,1,Caught,Abhishek Sharma,0,1,3,1
11,10_SHvsLSG,April 05,15:30:02,0,6,Mohammed Shami,Abhishek Sharma,0,0,0,N/A,0,1,Caught,Abhishek Sharma,0,1,3,2
12,10_SHvsLSG,April 05,15:30:02,1,1,Digvesh Singh Rathi,Travis Head,4,0,0,N/A,0,0,Not Out,N/A,4,1,7,2
13,10_SHvsLSG,April 05,15:30:02,1,2,Digvesh Singh Rathi,Travis Head,1,0,0,N/A,0,0,Not Out,N/A,1,1,8,2
14,10_SHvsLSG,April 05,15:30:02,1,3,Digvesh Singh Rathi,Ishan Kishan,0,0,0,N/A,0,0,Not Out,N/A,0,1,8,2
15,10_SHvsLSG,April 05,15:30:02,1,4,Digvesh Singh Rathi,Ishan Kishan,0,0,0,N/A,0,0,Not Out,N/A,0,1,8,2
16,10_SHvsLSG,April 05,15:30:02,1,5,Digvesh Singh Rathi,Ishan Kishan,1,0,0,N/A,0,0,Not Out,N/A,1,1,9,2
17,10_SHvsLSG,April 05,15:30:02,1,5,Digvesh Singh Rathi,Ishan Kishan,1,0,0,N/A,0,0,Not Out,N/A,1,1,10,2
18,10_SHvsLSG,April 05,15:30:02,1,6,Digvesh Singh Rathi,Travis Head,1,0,0,N/A,0,0,Not Out,N/A,1,1,11,2
19,10_SHvsLSG,April 05,15:30:02,1,6,Digvesh Singh Rathi,Travis Head,1,0,0,N/A,0,0,Not Out,N/A,1,1,12,2
20,10_SHvsLSG,April 05,15:30:02,2,1,Mohammed Shami,Travis Head,0,0,0,N/A,0,1,Caught,Travis Head,0,1,12,3
21,10_SHvsLSG,April 05,15:30:02,1,6,Digvesh Singh Rathi,Travis Head,1,0,0,N/A,0,0,Not Out,N/A,1,1,13,3
22,10_SHvsLSG,April 05,15:30:02,2,1,Mohammed Shami,Travis Head,0,0,0,N/A,0,1,Caught,Travis Head,0,1,13,4
23,10_SHvsLSG,April 05,15:30:02,2,1,Mohammed Shami,Travis Head,0,0,0,N/A,0,1,Caught,Travis Head,0,1,13,5
24,10_SHvsLSG,April 05,15:30:02,2,2,Mohammed Shami,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,13,5
25,10_SHvsLSG,April 05,15:30:02,2,3,Mohammed Shami,Liam Livingstone,0,1,1,wide,1,0,Not Out,N/A,1,1,14,5
26,10_SHvsLSG,April 05,15:30:02,2,3,Mohammed Shami,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,14,5
27,10_SHvsLSG,April 05,15:30:02,2,4,Mohammed Shami,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,14,5
28,10_SHvsLSG,April 05,15:30:02,2,5,Mohammed Shami,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,14,5
29,10_SHvsLSG,April 05,15:30:02,2,5,Mohammed Shami,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,14,5
30,10_SHvsLSG,April 05,15:30:02,2,6,Mohammed Shami,Liam Livingstone,1,0,0,N/A,0,0,Not Out,N/A,1,1,15,5
31,10_SHvsLSG,April 05,15:30:02,2,6,Mohammed Shami,Liam Livingstone,1,0,0,N/A,0,0,Not Out,N/A,1,1,16,5
32,10_SHvsLSG,April 05,15:30:02,3,1,Prince Yadav,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,16,5
33,10_SHvsLSG,April 05,15:30:02,3,1,Prince Yadav,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,16,5
34,10_SHvsLSG,April 05,15:30:02,3,2,Prince Yadav,Liam Livingstone,1,0,0,N/A,0,0,Not Out,N/A,1,1,17,5
35,10_SHvsLSG,April 05,15:30:02,3,2,Prince Yadav,Liam Livingstone,1,0,0,N/A,0,0,Not Out,N/A,1,1,18,5
36,10_SHvsLSG,April 05,15:30:02,3,3,Prince Yadav,Ishan Kishan,0,0,0,N/A,0,1,Bowled!!,Ishan Kishan,0,1,18,6
37,10_SHvsLSG,April 05,15:30:02,3,2,Prince Yadav,Liam Livingstone,1,0,0,N/A,0,0,Not Out,N/A,1,1,19,6
38,10_SHvsLSG,April 05,15:30:02,3,3,Prince Yadav,Ishan Kishan,0,0,0,N/A,0,1,Bowled!!,Ishan Kishan,0,1,19,7
39,10_SHvsLSG,April 05,15:30:02,3,4,Prince Yadav,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,19,7
40,10_SHvsLSG,April 05,15:30:02,3,5,Prince Yadav,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,19,7
41,10_SHvsLSG,April 05,15:30:02,3,5,Prince Yadav,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,19,7
42,10_SHvsLSG,April 05,15:30:02,3,6,Prince Yadav,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,19,7
43,10_SHvsLSG,April 05,15:30:02,4,1,Mohammed Shami,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,19,7
44,10_SHvsLSG,April 05,15:30:02,4,2,Mohammed Shami,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,19,7
45,10_SHvsLSG,April 05,15:30:02,4,2,Mohammed Shami,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,19,7
46,10_SHvsLSG,April 05,15:30:02,4,3,Mohammed Shami,Liam Livingstone,2,0,0,N/A,0,0,Not Out,N/A,2,1,21,7
47,10_SHvsLSG,April 05,15:30:02,4,3,Mohammed Shami,Liam Livingstone,2,0,0,N/A,0,0,Not Out,N/A,2,1,23,7
48,10_SHvsLSG,April 05,15:30:02,4,4,Mohammed Shami,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,23,7
49,10_SHvsLSG,April 05,15:30:02,4,5,Mohammed Shami,Liam Livingstone,2,0,0,N/A,0,0,Not Out,N/A,2,1,25,7
50,10_SHvsLSG,April 05,15:30:02,4,6,Mohammed Shami,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,25,7
51,10_SHvsLSG,April 05,15:30:02,4,5,Mohammed Shami,Liam Livingstone,2,0,0,N/A,0,0,Not Out,N/A,2,1,27,7
52,10_SHvsLSG,April 05,15:30:02,4,6,Mohammed Shami,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,27,7
53,10_SHvsLSG,April 05,15:30:02,5,1,Manimaran Siddharth,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,27,7
54,10_SHvsLSG,April 05,15:30:02,5,2,Manimaran Siddharth,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,27,7
55,10_SHvsLSG,April 05,15:30:02,5,4,Manimaran Siddharth,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,27,7
56,10_SHvsLSG,April 05,15:30:02,5,5,Manimaran Siddharth,Liam Livingstone,6,0,0,N/A,0,0,Not Out,N/A,6,1,33,7
57,10_SHvsLSG,April 05,15:30:02,5,5,Manimaran Siddharth,Liam Livingstone,6,0,0,N/A,0,0,Not Out,N/A,6,1,39,7
58,10_SHvsLSG,April 05,15:30:02,5,6,Manimaran Siddharth,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,39,7
59,10_SHvsLSG,April 05,15:30:02,5,6,Manimaran Siddharth,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,39,7
60,10_SHvsLSG,April 05,15:30:02,6,1,Avesh Khan,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,39,7
61,10_SHvsLSG,April 05,15:30:02,6,1,Avesh Khan,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,39,7
62,10_SHvsLSG,April 05,15:30:02,6,2,Avesh Khan,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,40,7
63,10_SHvsLSG,April 05,15:30:02,6,3,Avesh Khan,Liam Livingstone,1,0,0,N/A,0,0,Not Out,N/A,1,1,41,7
64,10_SHvsLSG,April 05,15:30:02,6,4,Avesh Khan,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,42,7
65,10_SHvsLSG,April 05,15:30:02,6,4,Avesh Khan,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,43,7
66,10_SHvsLSG,April 05,15:30:02,6,5,Avesh Khan,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,43,7
67,10_SHvsLSG,April 05,15:30:02,6,5,Avesh Khan,Liam Livingstone,0,0,0,N/A,0,0,Not Out,N/A,0,1,43,7
68,10_SHvsLSG,April 05,15:30:02,6,6,Avesh Khan,Liam Livingstone,1,0,0,N/A,0,0,Not Out,N/A,1,1,44,7
69,10_SHvsLSG,April 05,15:30:02,6,6,Avesh Khan,Liam Livingstone,1,0,0,N/A,0,0,Not Out,N/A,1,1,45,7
70,10_SHvsLSG,April 05,15:30:02,7,1,Digvesh Singh Rathi,Liam Livingstone,0,0,0,N/A,0,1,Caught,Liam Livingstone,0,1,45,8
71,10_SHvsLSG,April 05,15:30:02,7,1,Digvesh Singh Rathi,Liam Livingstone,0,0,0,N/A,0,1,Caught,Liam Livingstone,0,1,45,9
72,10_SHvsLSG,April 05,15:30:02,7,2,Digvesh Singh Rathi,Nitish Reddy,0,0,0,N/A,0,0,Not Out,N/A,0,1,45,9
73,10_SHvsLSG,April 05,15:30:02,7,3,Digvesh Singh Rathi,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,46,9
74,10_SHvsLSG,April 05,15:30:02,7,4,Digvesh Singh Rathi,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,47,9
75,10_SHvsLSG,April 05,15:30:02,7,5,Digvesh Singh Rathi,Nitish Reddy,0,0,0,N/A,0,0,Not Out,N/A,0,1,47,9
76,10_SHvsLSG,April 05,15:30:02,7,6,Digvesh Singh Rathi,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,48,9
77,10_SHvsLSG,April 05,15:30:02,7,5,Digvesh Singh Rathi,Nitish Reddy,0,0,0,N/A,0,0,Not Out,N/A,0,1,48,9
78,10_SHvsLSG,April 05,15:30:02,7,6,Digvesh Singh Rathi,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,49,9
79,10_SHvsLSG,April 05,15:30:02,8,1,Mohammed Shami,Nitish Reddy,0,0,0,N/A,0,0,Not Out,N/A,0,1,49,9
80,10_SHvsLSG,April 05,15:30:02,8,2,Mohammed Shami,Nitish Reddy,0,0,0,N/A,0,0,Not Out,N/A,0,1,49,9
81,10_SHvsLSG,April 05,15:30:02,8,3,Mohammed Shami,Nitish Reddy,0,0,0,N/A,0,0,Not Out,N/A,0,1,49,9
82,10_SHvsLSG,April 05,15:30:02,8,4,Mohammed Shami,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,50,9
83,10_SHvsLSG,April 05,15:30:02,8,4,Mohammed Shami,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,51,9
84,10_SHvsLSG,April 05,15:30:02,8,5,Mohammed Shami,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,52,9
85,10_SHvsLSG,April 05,15:30:02,8,5,Mohammed Shami,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,53,9
86,10_SHvsLSG,April 05,15:30:02,8,6,Mohammed Shami,Nitish Reddy,0,0,0,N/A,0,0,Not Out,N/A,0,1,53,9
87,10_SHvsLSG,April 05,15:30:02,8,5,Mohammed Shami,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,54,9
88,10_SHvsLSG,April 05,15:30:02,8,6,Mohammed Shami,Nitish Reddy,0,0,0,N/A,0,0,Not Out,N/A,0,1,54,9
89,10_SHvsLSG,April 05,15:30:02,8,5,Mohammed Shami,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,55,9
90,10_SHvsLSG,April 05,15:30:02,8,6,Mohammed Shami,Nitish Reddy,0,0,0,N/A,0,0,Not Out,N/A,0,1,55,9
91,10_SHvsLSG,April 05,15:30:02,8,5,Mohammed Shami,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,56,9
92,10_SHvsLSG,April 05,15:30:02,8,6,Mohammed Shami,Nitish Reddy,0,0,0,N/A,0,0,Not Out,N/A,0,1,56,9
93,10_SHvsLSG,April 05,15:30:02,9,1,Manimaran Siddharth,Heinrich Klaasen,3,0,0,N/A,0,0,Not Out,N/A,3,1,59,9
94,10_SHvsLSG,April 05,15:30:02,9,2,Manimaran Siddharth,Nitish Reddy,0,0,0,N/A,0,0,Not Out,N/A,0,1,59,9
95,10_SHvsLSG,April 05,15:30:02,9,4,Manimaran Siddharth,Nitish Reddy,0,0,0,N/A,0,0,Not Out,N/A,0,1,59,9
96,10_SHvsLSG,April 05,15:30:02,9,5,Manimaran Siddharth,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,60,9
97,10_SHvsLSG,April 05,15:30:02,9,5,Manimaran Siddharth,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,61,9
98,10_SHvsLSG,April 05,15:30:02,9,6,Manimaran Siddharth,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,61,9
99,10_SHvsLSG,April 05,15:30:02,9,5,Manimaran Siddharth,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,62,9
100,10_SHvsLSG,April 05,15:30:02,9,6,Manimaran Siddharth,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,62,9
101,10_SHvsLSG,April 05,15:30:02,9,5,Manimaran Siddharth,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,63,9
102,10_SHvsLSG,April 05,15:30:02,9,6,Manimaran Siddharth,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,63,9
103,10_SHvsLSG,April 05,15:30:02,10,1,Prince Yadav,Nitish Reddy,6,0,0,N/A,0,0,Not Out,N/A,6,1,69,9
104,10_SHvsLSG,April 05,15:30:02,10,2,Prince Yadav,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,70,9
105,10_SHvsLSG,April 05,15:30:02,10,3,Prince Yadav,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,71,9
106,10_SHvsLSG,April 05,15:30:02,10,4,Prince Yadav,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,72,9
107,10_SHvsLSG,April 05,15:30:02,10,4,Prince Yadav,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,73,9
108,10_SHvsLSG,April 05,15:30:02,10,5,Prince Yadav,Heinrich Klaasen,6,0,0,N/A,0,0,Not Out,N/A,6,1,79,9
109,10_SHvsLSG,April 05,15:30:02,10,5,Prince Yadav,Heinrich Klaasen,6,0,0,N/A,0,0,Not Out,N/A,6,1,85,9
110,10_SHvsLSG,April 05,15:30:02,10,6,Prince Yadav,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,86,9
111,10_SHvsLSG,April 05,15:30:02,10,6,Prince Yadav,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,87,9
112,10_SHvsLSG,April 05,15:30:02,11,1,Digvesh Singh Rathi,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,88,9
113,10_SHvsLSG,April 05,15:30:02,11,2,Digvesh Singh Rathi,Nitish Reddy,4,0,0,N/A,0,0,Not Out,N/A,4,1,92,9
114,10_SHvsLSG,April 05,15:30:02,11,3,Digvesh Singh Rathi,Nitish Reddy,4,0,0,N/A,0,0,Not Out,N/A,4,1,96,9
115,10_SHvsLSG,April 05,15:30:02,11,3,Digvesh Singh Rathi,Nitish Reddy,4,0,0,N/A,0,0,Not Out,N/A,4,1,100,9
116,10_SHvsLSG,April 05,15:30:02,11,4,Digvesh Singh Rathi,Nitish Reddy,2,0,0,N/A,0,0,Not Out,N/A,2,1,102,9
117,10_SHvsLSG,April 05,15:30:02,11,5,Digvesh Singh Rathi,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,103,9
118,10_SHvsLSG,April 05,15:30:02,11,6,Digvesh Singh Rathi,Heinrich Klaasen,2,0,0,N/A,0,0,Not Out,N/A,2,1,105,9
119,10_SHvsLSG,April 05,15:30:02,11,5,Digvesh Singh Rathi,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,106,9
120,10_SHvsLSG,April 05,15:30:02,11,6,Digvesh Singh Rathi,Heinrich Klaasen,2,0,0,N/A,0,0,Not Out,N/A,2,1,108,9
121,10_SHvsLSG,April 05,15:30:02,12,1,Manimaran Siddharth,Nitish Reddy,4,0,0,N/A,0,0,Not Out,N/A,4,1,112,9
122,10_SHvsLSG,April 05,15:30:02,12,2,Manimaran Siddharth,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,113,9
123,10_SHvsLSG,April 05,15:30:02,12,2,Manimaran Siddharth,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,114,9
124,10_SHvsLSG,April 05,15:30:02,12,3,Manimaran Siddharth,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,115,9
125,10_SHvsLSG,April 05,15:30:02,12,4,Manimaran Siddharth,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,116,9
126,10_SHvsLSG,April 05,15:30:02,12,5,Manimaran Siddharth,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,116,9
127,10_SHvsLSG,April 05,15:30:02,12,5,Manimaran Siddharth,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,116,9
128,10_SHvsLSG,April 05,15:30:02,12,6,Manimaran Siddharth,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,117,9
129,10_SHvsLSG,April 05,15:30:02,12,6,Manimaran Siddharth,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,118,9
130,10_SHvsLSG,April 05,15:30:02,13,1,Avesh Khan,Heinrich Klaasen,4,0,0,N/A,0,0,Not Out,N/A,4,1,122,9
131,10_SHvsLSG,April 05,15:30:02,13,1,Avesh Khan,Heinrich Klaasen,4,0,0,N/A,0,0,Not Out,N/A,4,1,126,9
132,10_SHvsLSG,April 05,15:30:02,13,2,Avesh Khan,Heinrich Klaasen,4,0,0,N/A,0,0,Not Out,N/A,4,1,130,9
133,10_SHvsLSG,April 05,15:30:02,13,3,Avesh Khan,Heinrich Klaasen,2,0,0,N/A,0,0,Not Out,N/A,2,1,132,9
134,10_SHvsLSG,April 05,15:30:02,13,4,Avesh Khan,Heinrich Klaasen,4,0,0,N/A,0,0,Not Out,N/A,4,1,136,9
135,10_SHvsLSG,April 05,15:30:02,13,4,Avesh Khan,Heinrich Klaasen,4,0,0,N/A,0,0,Not Out,N/A,4,1,140,9
136,10_SHvsLSG,April 05,15:30:02,13,5,Avesh Khan,Heinrich Klaasen,4,0,0,N/A,0,0,Not Out,N/A,4,1,144,9
137,10_SHvsLSG,April 05,15:30:02,13,5,Avesh Khan,Heinrich Klaasen,4,0,0,N/A,0,0,Not Out,N/A,4,1,148,9
138,10_SHvsLSG,April 05,15:30:02,13,6,Avesh Khan,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,149,9
139,10_SHvsLSG,April 05,15:30:02,13,6,Avesh Khan,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,150,9
140,10_SHvsLSG,April 05,15:30:02,14,1,Digvesh Singh Rathi,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,151,9
141,10_SHvsLSG,April 05,15:30:02,14,2,Digvesh Singh Rathi,Nitish Reddy,6,0,0,N/A,0,0,Not Out,N/A,6,1,157,9
142,10_SHvsLSG,April 05,15:30:02,14,3,Digvesh Singh Rathi,Nitish Reddy,6,0,0,N/A,0,0,Not Out,N/A,6,1,163,9
143,10_SHvsLSG,April 05,15:30:02,14,4,Digvesh Singh Rathi,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,164,9
144,10_SHvsLSG,April 05,15:30:02,14,5,Digvesh Singh Rathi,Heinrich Klaasen,0,1,1,wide,1,0,Not Out,N/A,1,1,165,9
145,10_SHvsLSG,April 05,15:30:02,14,4,Digvesh Singh Rathi,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,166,9
146,10_SHvsLSG,April 05,15:30:02,14,5,Digvesh Singh Rathi,Heinrich Klaasen,0,1,1,wide,1,0,Not Out,N/A,1,1,167,9
147,10_SHvsLSG,April 05,15:30:02,14,5,Digvesh Singh Rathi,Heinrich Klaasen,0,1,1,wide,1,0,Not Out,N/A,1,1,168,9
148,10_SHvsLSG,April 05,15:30:02,14,5,Digvesh Singh Rathi,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,169,9
149,10_SHvsLSG,April 05,15:30:02,14,5,Digvesh Singh Rathi,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,170,9
150,10_SHvsLSG,April 05,15:30:02,14,6,Digvesh Singh Rathi,Nitish Reddy,6,0,0,N/A,0,0,Not Out,N/A,6,1,176,9
151,10_SHvsLSG,April 05,15:30:02,14,6,Digvesh Singh Rathi,Nitish Reddy,6,0,0,N/A,0,0,Not Out,N/A,6,1,182,9
152,10_SHvsLSG,April 05,15:30:02,15,1,Prince Yadav,Heinrich Klaasen,6,0,0,N/A,0,0,Not Out,N/A,6,1,188,9
153,10_SHvsLSG,April 05,15:30:02,14,6,Digvesh Singh Rathi,Nitish Reddy,6,0,0,N/A,0,0,Not Out,N/A,6,1,194,9
154,10_SHvsLSG,April 05,15:30:02,15,1,Prince Yadav,Heinrich Klaasen,6,0,0,N/A,0,0,Not Out,N/A,6,1,200,9
155,10_SHvsLSG,April 05,15:30:02,15,3,Prince Yadav,Nitish Reddy,0,0,0,N/A,0,0,Not Out,N/A,0,1,200,9
156,10_SHvsLSG,April 05,15:30:02,15,4,Prince Yadav,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,201,9
157,10_SHvsLSG,April 05,15:30:02,15,5,Prince Yadav,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,201,9
158,10_SHvsLSG,April 05,15:30:02,15,6,Prince Yadav,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,202,9
159,10_SHvsLSG,April 05,15:30:02,15,5,Prince Yadav,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,202,9
160,10_SHvsLSG,April 05,15:30:02,15,6,Prince Yadav,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,203,9
161,10_SHvsLSG,April 05,15:30:02,15,5,Prince Yadav,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,203,9
162,10_SHvsLSG,April 05,15:30:02,15,6,Prince Yadav,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,204,9
163,10_SHvsLSG,April 05,15:30:02,15,5,Prince Yadav,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,204,9
164,10_SHvsLSG,April 05,15:30:02,15,6,Prince Yadav,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,205,9
165,10_SHvsLSG,April 05,15:30:02,15,5,Prince Yadav,Heinrich Klaasen,0,0,0,N/A,0,0,Not Out,N/A,0,1,205,9
166,10_SHvsLSG,April 05,15:30:02,15,6,Prince Yadav,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,206,9
167,10_SHvsLSG,April 05,15:30:02,15,6,Prince Yadav,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,207,9
168,10_SHvsLSG,April 05,15:30:02,16,1,Avesh Khan,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,208,9
169,10_SHvsLSG,April 05,15:30:02,16,2,Avesh Khan,Nitish Reddy,1,0,0,N/A,0,0,Not Out,N/A,1,1,209,9
170,10_SHvsLSG,April 05,15:30:02,16,3,Avesh Khan,Heinrich Klaasen,2,0,0,N/A,0,0,Not Out,N/A,2,1,211,9
171,10_SHvsLSG,April 05,15:30:02,16,3,Avesh Khan,Heinrich Klaasen,2,0,0,N/A,0,0,Not Out,N/A,2,1,213,9
172,10_SHvsLSG,April 05,15:30:02,16,4,Avesh Khan,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,214,9
173,10_SHvsLSG,April 05,15:30:02,16,5,Avesh Khan,Nitish Reddy,0,0,0,N/A,0,0,Not Out,N/A,0,1,214,9
174,10_SHvsLSG,April 05,15:30:02,16,6,Avesh Khan,Nitish Reddy,6,0,0,N/A,0,0,Not Out,N/A,6,1,220,9
175,10_SHvsLSG,April 05,15:30:02,16,6,Avesh Khan,Nitish Reddy,6,0,0,N/A,0,0,Not Out,N/A,6,1,226,9
176,10_SHvsLSG,April 05,15:30:02,17,1,Manimaran Siddharth,Heinrich Klaasen,4,0,0,N/A,0,0,Not Out,N/A,4,1,230,9
177,10_SHvsLSG,April 05,15:30:02,17,2,Manimaran Siddharth,Heinrich Klaasen,2,0,0,N/A,0,0,Not Out,N/A,2,1,232,9
178,10_SHvsLSG,April 05,15:30:02,17,3,Manimaran Siddharth,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,233,9
179,10_SHvsLSG,April 05,15:30:02,17,3,Manimaran Siddharth,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,234,9
180,10_SHvsLSG,April 05,15:30:02,17,4,Manimaran Siddharth,Nitish Reddy,0,1,1,wide,1,0,Not Out,N/A,1,1,235,9
181,10_SHvsLSG,April 05,15:30:02,17,4,Manimaran Siddharth,Nitish Reddy,0,1,1,wide,1,0,Not Out,N/A,1,1,236,9
182,10_SHvsLSG,April 05,15:30:02,17,4,Manimaran Siddharth,Nitish Reddy,0,0,0,N/A,0,1,Caught,Nitish Reddy,0,1,236,10
183,10_SHvsLSG,April 05,15:30:02,17,4,Manimaran Siddharth,Nitish Reddy,0,0,0,N/A,0,1,Caught,Nitish Reddy,0,1,236,11
184,10_SHvsLSG,April 05,15:30:02,17,5,Manimaran Siddharth,Aniket Verma,1,0,0,N/A,0,0,Not Out,N/A,1,1,237,11
185,10_SHvsLSG,April 05,15:30:02,17,5,Manimaran Siddharth,Aniket Verma,1,0,0,N/A,0,0,Not Out,N/A,1,1,238,11
186,10_SHvsLSG,April 05,15:30:02,17,6,Manimaran Siddharth,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,239,11
187,10_SHvsLSG,April 05,15:30:02,17,6,Manimaran Siddharth,Heinrich Klaasen,1,0,0,N/A,0,0,Not Out,N/A,1,1,240,11
188,10_SHvsLSG,April 05,15:30:02,18,1,Avesh Khan,Heinrich Klaasen,0,0,0,N/A,0,1,Caught,Heinrich Klaasen,0,1,240,12
189,10_SHvsLSG,April 05,15:30:02,18,1,Avesh Khan,Heinrich Klaasen,0,0,0,N/A,0,1,Caught,Heinrich Klaasen,0,1,240,13